In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [3]:
#IMPORT THE NYERI DATASETS
df=pd.read_excel('datasets/nyeri.xlsx')

In [5]:
df.dtypes

student_name                            object
student_class                              str
student_course                             str
student_year                           float64
student_gender                             str
student_category                           str
student_adm_no                          object
attachment_period                          str
year                                   float64
attachment_start_date                      str
attachment_end_date                        str
company_name                               str
sector_name                                str
placement_status                           str
graded                                     str
assigned_manual                            str
student_workbehaviour_grading_score    float64
student_skills_grading_score           float64
student_knowledge_grading_score        float64
student_final_score                    float64
dtype: object

In [9]:
df['student_name']=df['student_name'].astype(str)
df['student_year']=pd.to_numeric(df['student_year'],errors='coerce').astype('Int64')
df['student_adm_no']=pd.to_numeric(df['student_adm_no'],errors='coerce').astype('Int64')
df['year']=pd.to_numeric(df['year'],errors='coerce').astype('Int64')
df['attachment_start_date']=pd.to_datetime(df['attachment_start_date'],errors='coerce')
df['attachment_end_date']=pd.to_datetime(df['attachment_end_date'],errors='coerce')

In [10]:
df.dtypes

student_name                                      str
student_class                                     str
student_course                                    str
student_year                                    Int64
student_gender                                    str
student_category                                  str
student_adm_no                                  Int64
attachment_period                                 str
year                                            Int64
attachment_start_date                  datetime64[us]
attachment_end_date                    datetime64[us]
company_name                                      str
sector_name                                       str
placement_status                                  str
graded                                            str
assigned_manual                                   str
student_workbehaviour_grading_score           float64
student_skills_grading_score                  float64
student_knowledge_grading_score               float64
student_final_score                           float64
dtype: object

In [12]:
df.head(5)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,54056,sept-dec,2025,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,51732,sept-dec,2025,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,53862,sept-dec,2025,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,51609,sept-dec,2025,2025-09-01,2025-12-31,KENYA POWER NYERI,"Electrical & Electronics Engineering, Electric...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0
4,James Mugendi Mugi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,53842,sept-dec,2025,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,Electrical & Electronics Engineering,Placed,Graded,Assigned,20.0,42.9,16.7,80.0

In [13]:
df['student_name']=df['student_name'].str.strip().str.upper()

In [14]:
df.head(5)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,ALLAN THIGA MAINA,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,54056,sept-dec,2025,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
1,BERNAD NDIRANGU MWANGI,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,51732,sept-dec,2025,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0
2,ISAAC KANJA KABUCHU,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,53862,sept-dec,2025,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
3,ISAAC KIHAGI BIRU,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,51609,sept-dec,2025,2025-09-01,2025-12-31,KENYA POWER NYERI,"Electrical & Electronics Engineering, Electric...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0
4,JAMES MUGENDI MUGI,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,Male,CBS,53842,sept-dec,2025,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,Electrical & Electronics Engineering,Placed,Graded,Assigned,20.0,42.9,16.7,80.0

In [20]:
string_cloumns=df.select_dtypes(include=['string']).columns
df[string_cloumns]=df[string_cloumns].apply(
    lambda col:col.str.strip().str.upper()
)

In [21]:
df.head(5)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,ALLAN THIGA MAINA,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,MALE,CBS,54056,SEPT-DEC,2025,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,NOT GRADED,ASSIGNED,10.0,38.6,NaN,NaN
1,BERNAD NDIRANGU MWANGI,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,MALE,CBS,51732,SEPT-DEC,2025,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, HEALTH CARE GIVER, HEALTHCARE...",PLACED,GRADED,ASSIGNED,20.0,51.4,15.0,86.0
2,ISAAC KANJA KABUCHU,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,MALE,CBS,53862,SEPT-DEC,2025,2025-09-01,2025-12-31,NYERI RURINGU,NaN,PLACED,NOT GRADED,ASSIGNED,NaN,NaN,NaN,NaN
3,ISAAC KIHAGI BIRU,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,MALE,CBS,51609,SEPT-DEC,2025,2025-09-01,2025-12-31,KENYA POWER NYERI,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,GRADED,ASSIGNED,20.0,60.0,20.0,100.0
4,JAMES MUGENDI MUGI,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,MALE,CBS,53842,SEPT-DEC,2025,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,ELECTRICAL & ELECTRONICS ENGINEERING,PLACED,GRADED,ASSIGNED,20.0,42.9,16.7,80.0

In [22]:
df['student_gender'].value_counts()

student_gender
MALE       10256
FEMALE      6241
F            278
M            184
FE4MALE        1
Name: count, dtype: int64

In [23]:
df['student_gender']=df['student_gender'].map({
    'M':'MALE',
    'F':'FEMALE',
    'FE4MALE':'FEMALE'
})

In [24]:
df['student_gender'].value_counts()

student_gender
FEMALE    279
MALE      184
Name: count, dtype: int64

In [27]:
df[df['student_gender']=='MALE']

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
1716,ALLAN NDEGWA KARIUKI,NNP/BDT6/23S1,BUILDING TECHNICIAN LEVEL 6,1,MALE,CBS,44454,SEP - DEC,2024,2024-09-01,2024-12-31,BRITISH ARMY TRAINING UNIT KENYA (BATUK),"AEROSPACE AND DEFENSE, AUTOMOTIVE SECTOR",PLACED,GRADED,ASSIGNED,20.0,60.0,20.0,100.0
1770,ELVIS WAMBUGU MATU,NNP/BDT6/23S1,BUILDING TECHNICIAN LEVEL 6,1,MALE,CBS,43480,SEP - DEC,2024,2024-09-01,2024-12-31,COUNTY GOVERNMENT OF NYERI,"BUILDING TECHNICIAN, CONSTRUCTION AND ENGINEER...",PLACED,NOT GRADED,ASSIGNED,NaN,NaN,NaN,NaN
2622,ALLAN KARIUKI WANGECI,CBT23J1,CERTIFICATE IN BUILDING TECHNOLOGY,1,MALE,KNEC,19794,JANUARY - APRIL,2024,2024-01-01,2024-04-30,AYDEN HOME CONSTRUCTION SITE,NaN,PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
2625,AZARIUS GAKURU WAMOKO,CBT22S1,CERTIFICATE IN BUILDING TECHNOLOGY,1,MALE,KNEC,38808,SEPT - NOV,2023,2023-09-01,2023-11-30,KENYA NATIONAL HIGHWAYS AUTHORITY - RURING'U,"BUILDING TECHNICIAN, BUILDING TECHNOLOGY, CIVI...",PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
2630,CHANZERA ANGORE GEORGE,CBT22S1,CERTIFICATE IN BUILDING TECHNOLOGY,1,MALE,KNEC,41105,SEPT - NOV,2023,2023-09-01,2023-11-30,EPCO BUILDERS LIMITED,"BUILDING TECHNICIAN, BUILDING TECHNOLOGY, CIVI...",PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17438,BRIAN MWANGI GITUI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,37571,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17442,DENNIS NDIRANGU WAMBUI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38571,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17446,GEOFFREY MUCHEKE KANG`ETHE,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38638,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17462,STEPHEN WERU GICHUKI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38620,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17467,WANGONDU WAMUCII SAMUEL,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38489,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN

In [28]:
df['year'].value_counts()

year
2025    5536
2024    3836
2023    2959
2026    2820
Name: count, dtype: Int64

In [35]:
df1=df[(df['student_gender']=='MALE') | (df['year']==2025)]
len(df1)

5708

In [41]:
df.loc[
    (df['student_gender']=='FEMALE') & (df['year']==2025),
    ['student_name','student_gender','student_class','year']
]

                   student_name student_gender  student_class  year
12649  CHRISTINE NYAMBURA MAINA         FEMALE  NNP/BDT6/23S1  2025
13519  PETRONELA GATHONI KARUKU         FEMALE        DBT24J2  2025

In [48]:
df.loc[
    (df['student_year']<=2) | (df['year']>=2023),
    ['student_name','student_year','year']
]

                   student_name  student_year  year
0             ALLAN THIGA MAINA             1  2025
1        BERNAD NDIRANGU MWANGI             1  2025
2           ISAAC KANJA KABUCHU             1  2025
3             ISAAC KIHAGI BIRU             1  2025
4            JAMES MUGENDI MUGI             1  2025
...                         ...           ...   ...
17562  PATRICK KARIUKI GACHOMBA             1  2025
17563         PETER MAINA WANJA             1  2025
17564     BENJAMIN  KIOKO  PAUL             1  2026
17565     DAVID MURIITHI ABWAVO             1  2026
17566            MICHAE CHEPTOO          <NA>  2025

[15151 rows x 3 columns]

In [56]:
df.loc[
    (df['student_year'].isin([1,2])) & (df['year'].isin([2023,2024])) & (df['student_gender'].isin(['FEMALE','MALE']))
]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
111,MARGARET NYAMBURA MURIITHI,AFGM22S1,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...,1,FEMALE,KNEC,39210,SEPT - NOV,2023,2023-09-01,2023-11-30,EBENEZAH FASHION SHOP,"FASHION AND APPAREL, FASHION DESIGN OPERATOR, ...",PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
112,MARY WANGARI KITHUMBU,AFGM22S1,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...,1,FEMALE,KNEC,39475,SEPT - NOV,2023,2023-09-01,2023-11-30,NOKRAS SILVEROAK EMBU,"CATERING AND ACCOMMODATION, FOOD & BEVERAGE PR...",PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
113,MEDRINE MWENDE MUTEMBEI,AFGM22S1,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...,1,FEMALE,KNEC,39296,SEPT - NOV,2023,2023-09-01,2023-11-30,GIFTED HANDS DRESSMAKING,"FASHION AND APPAREL, FASHION DESIGN OPERATOR, ...",PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
1716,ALLAN NDEGWA KARIUKI,NNP/BDT6/23S1,BUILDING TECHNICIAN LEVEL 6,1,MALE,CBS,44454,SEP - DEC,2024,2024-09-01,2024-12-31,BRITISH ARMY TRAINING UNIT KENYA (BATUK),"AEROSPACE AND DEFENSE, AUTOMOTIVE SECTOR",PLACED,GRADED,ASSIGNED,20.0,60.0,20.0,100.0
1770,ELVIS WAMBUGU MATU,NNP/BDT6/23S1,BUILDING TECHNICIAN LEVEL 6,1,MALE,CBS,43480,SEP - DEC,2024,2024-09-01,2024-12-31,COUNTY GOVERNMENT OF NYERI,"BUILDING TECHNICIAN, CONSTRUCTION AND ENGINEER...",PLACED,NOT GRADED,ASSIGNED,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17446,GEOFFREY MUCHEKE KANG`ETHE,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38638,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17455,LUCY NJOKI WARUTERE,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,FEMALE,KNEC,37334,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17456,MAXMIRRIAN MURUGI KARIUKI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,FEMALE,KNEC,38265,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17462,STEPHEN WERU GICHUKI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38620,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17467,WANGONDU WAMUCII SAMUEL,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2),1,MALE,KNEC,38489,SEPT - NOV,2023,2023-09-01,2023-11-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN

In [60]:
df.loc[
    df['student_year'].isin([3])
]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
1182,BONIFACE NG'ANG'A MWAI,AET6/24J3,AUTOMOTIVE TECHNICIAN LEVEL 6,3,NaN,CBET,37650,AUGUST-NOVEMBER,2023,2023-09-09,2023-12-28,DIANA NYERI,"PROFESSIONAL SERVICES (CONSULTING, LEGAL, ACCO...",PLACED,NOT GRADED,ASSIGNED,NaN,60.0,13.3,NaN
1183,CHRISTINE WANGUI WAIRIMU,AET6/24J3,AUTOMOTIVE TECHNICIAN LEVEL 6,3,NaN,CBET,37554,AUGUST-NOVEMBER,2023,2023-09-09,2023-12-28,BRADSHAWS OF MOUNT KENYA LTD,"INDUSTRIAL MECHATRONICS, MECHANICAL ENGINEERIN...",PLACED,NOT GRADED,ASSIGNED,NaN,56.8,20.0,NaN
1184,CLINTON GITONGA NYAGAH,AET6/24J3,AUTOMOTIVE TECHNICIAN LEVEL 6,3,NaN,CBET,36934,AUGUST-NOVEMBER,2023,2023-09-09,2023-12-28,DALLAS AUTO CARE,"AUTOMOTIVE TECHNICIAN, MOTOR VEHICLE MECHANICS",PLACED,GRADED,ASSIGNED,0.0,60.0,20.0,80.0
1185,COLLINS MUTUGI NJERU,AET6/24J3,AUTOMOTIVE TECHNICIAN LEVEL 6,3,NaN,CBET,37165,AUGUST-NOVEMBER,2023,2023-09-09,2023-12-28,FELLOES WORKSHOP,"MECHANICAL ENGINEERING, MECHANICAL PRODUCTION ...",PLACED,GRADED,ASSIGNED,0.0,60.0,20.0,80.0
1186,DAVID GITHINJI MAINA,AET6/24J3,AUTOMOTIVE TECHNICIAN LEVEL 6,3,NaN,CBET,38027,AUGUST-NOVEMBER,2023,2023-09-09,2023-12-28,KENYA VEHICLE MANUFACTURERS,"AUTOMOTIVE & ELECTRONICS ENGINEERING, AUTOMOTI...",PLACED,NOT GRADED,ASSIGNED,NaN,55.3,20.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14563,NJOKI MUSA SARAH,NNP/FDM6/25M3,FASHION DESIGN TECHNICIAN LEVEL 6,3,NaN,CBS,41315,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17481,BENSON MURIMI MUGENDI,NNP/SLT6/25S3,SCIENCE LABORATORY TECHNICIAN LEVEL 6,3,NaN,CBS,44499,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17485,FAITH MBANDI MURIUKI,NNP/SLT6/25M3,SCIENCE LABORATORY TECHNICIAN LEVEL 6,3,NaN,CBET,42523,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17486,FLORENCE WANGARI NDIRANGU,NNP/SLT6/25M3,SCIENCE LABORATORY TECHNICIAN LEVEL 6,3,NaN,CBET,42603,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17489,MBATHA MUTUKU ALICE,NNP/SLT6/25S3,SCIENCE LABORATORY TECHNICIAN LEVEL 6,3,NaN,CBS,44394,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN

In [64]:
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [71]:
df.loc[
    ~df['student_final_score'].between(0,10),
    [
        'student_name',
        'student_workbehaviour_grading_score',
        'student_skills_grading_score',
        'student_knowledge_grading_score',
        'student_final_score'
    ]
]

,student_name,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,ALLAN THIGA MAINA,10.0,38.6,NaN,NaN
1,BERNAD NDIRANGU MWANGI,20.0,51.4,15.0,86.0
2,ISAAC KANJA KABUCHU,NaN,NaN,NaN,NaN
3,ISAAC KIHAGI BIRU,20.0,60.0,20.0,100.0
4,JAMES MUGENDI MUGI,20.0,42.9,16.7,80.0
...,...,...,...,...,...
17562,PATRICK KARIUKI GACHOMBA,NaN,NaN,NaN,NaN
17563,PETER MAINA WANJA,NaN,NaN,NaN,NaN
17564,BENJAMIN KIOKO PAUL,NaN,NaN,NaN,NaN
17565,DAVID MURIITHI ABWAVO,NaN,NaN,NaN,NaN
17566,MICHAE CHEPTOO,NaN,NaN,NaN,NaN

In [78]:
df.loc[
    df['company_name'].str.contains('kenya',case=False,na=False),
    ['student_name','student_class','company_name','student_final_score']
]

,student_name,student_class,company_name,student_final_score
3,ISAAC KIHAGI BIRU,NNP/EIT4/25J1,KENYA POWER NYERI,100.0
16,BENEDETA MUTHEU,CDACC/AGS6/24S1,KENYA FARMERS ASSOCIATION,100.0
56,BONFACE KAMAU MAINA,CDACC/ANC6/25J2,KENYA AGRICULTURAL AND LIVESTOCK RESEARCH ORGA...,NaN
131,DANSON MUNENE IRUNGU,AMVM22S1,KENYA AGRICULTURAL AND LIVESTOCK RESEARCH ORGA...,NaN
145,JOHN LEE WANJIRU,MVM424M1,VAN KAPPEL KENYA,80.0
...,...,...,...,...
12249,SUSAN NYAGUTHII MWANIKI,NNP/TTM5/24M2,KENYA WILDLIFE SERVICE NYERI,NaN
12250,WELGAR WANGARI WAIRIMU,NNP/TTM5/23J1,KENYA WILDLIFE SERVICE -LANG'ATA,100.0
12282,MARTIN KARANJA MWANGI,NNP/WF4/25S2-M,KENYA VEHICLE MANUFACTURERS,85.0
12291,MICHAEL MUGUMO KAMWARO,NNP/WFB5/25J2,BRADSHAWS OF MOUNT KENYA LTD,99.0
12292,MICHAEL MUGUMO KAMWARO,NNP/WFB5/25J2,BRADSHAWS OF MOUNT KENYA LTD,100.0

In [84]:
df.loc[
    df['company_name'].str.endswith('kenya',na=False)
]

Empty DataFrame
Columns: [student_name, student_class, student_course, student_year, student_gender, student_category, student_adm_no, attachment_period, year, attachment_start_date, attachment_end_date, company_name, sector_name, placement_status, graded, assigned_manual, student_workbehaviour_grading_score, student_skills_grading_score, student_knowledge_grading_score, student_final_score]
Index: []

In [89]:
df.loc[:,['student_name','student_class','student_final_score']]

                   student_name  student_class  student_final_score
0             ALLAN THIGA MAINA  NNP/EIT4/25J1                  NaN
1        BERNAD NDIRANGU MWANGI  NNP/EIT4/25J1                 86.0
2           ISAAC KANJA KABUCHU  NNP/EIT4/25J1                  NaN
3             ISAAC KIHAGI BIRU  NNP/EIT4/25J1                100.0
4            JAMES MUGENDI MUGI  NNP/EIT4/25J1                 80.0
...                         ...            ...                  ...
17562  PATRICK KARIUKI GACHOMBA       WFB424S1                  NaN
17563         PETER MAINA WANJA  NNP/WFB4/25J1                  NaN
17564     BENJAMIN  KIOKO  PAUL  NNP/WFB5/24S1                  NaN
17565     DAVID MURIITHI ABWAVO  NNP/WFB5/24S1                  NaN
17566            MICHAE CHEPTOO  NNP/WFB5/23S1                  NaN

[17567 rows x 3 columns]

In [90]:
df['graded'].value_counts()

graded
NOT GRADED    10476
GRADED         7091
Name: count, dtype: int64

In [97]:
df.loc[
     df['graded'].str.contains('GRADED'),
    ['student_name','student_class','placement_status','graded']
]

                   student_name  student_class placement_status      graded
0             ALLAN THIGA MAINA  NNP/EIT4/25J1           PLACED  NOT GRADED
1        BERNAD NDIRANGU MWANGI  NNP/EIT4/25J1           PLACED      GRADED
2           ISAAC KANJA KABUCHU  NNP/EIT4/25J1           PLACED  NOT GRADED
3             ISAAC KIHAGI BIRU  NNP/EIT4/25J1           PLACED      GRADED
4            JAMES MUGENDI MUGI  NNP/EIT4/25J1           PLACED      GRADED
...                         ...            ...              ...         ...
17562  PATRICK KARIUKI GACHOMBA       WFB424S1       NOT PLACED  NOT GRADED
17563         PETER MAINA WANJA  NNP/WFB4/25J1       NOT PLACED  NOT GRADED
17564     BENJAMIN  KIOKO  PAUL  NNP/WFB5/24S1       NOT PLACED  NOT GRADED
17565     DAVID MURIITHI ABWAVO  NNP/WFB5/24S1       NOT PLACED  NOT GRADED
17566            MICHAE CHEPTOO  NNP/WFB5/23S1       NOT PLACED  NOT GRADED

[17567 rows x 4 columns]

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  str
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  Int64
 4   student_gender                       463 non-null    str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17479 non-null  Int64
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  Int64
 9   attachment_start_date                15151 non-null  datetime64[us]
 10  attachment_end_date                  15151 non-null  datetime64[us]
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: Int64(3), datetime64[us](2), float64(4), str(11)
memory usage: 2.7 MB

In [101]:
df.iloc[:, [0,2,9,10]]

,student_name,student_course,attachment_start_date,attachment_end_date
0,ALLAN THIGA MAINA,ELECTRICAL INSTALLATION TECHNOLOGY,2025-09-01,2025-12-31
1,BERNAD NDIRANGU MWANGI,ELECTRICAL INSTALLATION TECHNOLOGY,2025-09-01,2025-12-31
2,ISAAC KANJA KABUCHU,ELECTRICAL INSTALLATION TECHNOLOGY,2025-09-01,2025-12-31
3,ISAAC KIHAGI BIRU,ELECTRICAL INSTALLATION TECHNOLOGY,2025-09-01,2025-12-31
4,JAMES MUGENDI MUGI,ELECTRICAL INSTALLATION TECHNOLOGY,2025-09-01,2025-12-31
...,...,...,...,...
17562,PATRICK KARIUKI GACHOMBA,WELDING AND FABRICATION LEVEL 4,2025-05-01,2025-08-31
17563,PETER MAINA WANJA,WELDING AND FABRICATION LEVEL 4,2025-09-01,2025-12-31
17564,BENJAMIN KIOKO PAUL,WELDING AND FABRICATION TECHNICIAN LEVEL 5,2026-01-01,2026-04-30
17565,DAVID MURIITHI ABWAVO,WELDING AND FABRICATION TECHNICIAN LEVEL 5,2026-01-01,2026-04-30
17566,MICHAE CHEPTOO,WELDING AND FABRICATION TECHNICIAN LEVEL 5,2025-05-01,2025-08-31

In [104]:
df.iloc[
    df['student_gender']=='MALE', 0:3,
]

,student_name,student_class,student_course
1716,ALLAN NDEGWA KARIUKI,NNP/BDT6/23S1,BUILDING TECHNICIAN LEVEL 6
1770,ELVIS WAMBUGU MATU,NNP/BDT6/23S1,BUILDING TECHNICIAN LEVEL 6
2622,ALLAN KARIUKI WANGECI,CBT23J1,CERTIFICATE IN BUILDING TECHNOLOGY
2625,AZARIUS GAKURU WAMOKO,CBT22S1,CERTIFICATE IN BUILDING TECHNOLOGY
2630,CHANZERA ANGORE GEORGE,CBT22S1,CERTIFICATE IN BUILDING TECHNOLOGY
...,...,...,...
17438,BRIAN MWANGI GITUI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2)
17442,DENNIS NDIRANGU WAMBUI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2)
17446,GEOFFREY MUCHEKE KANG`ETHE,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2)
17462,STEPHEN WERU GICHUKI,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2)
17467,WANGONDU WAMUCII SAMUEL,PLB/G2/23M1,PLUMBER PIPE FITTER (GRADE 2)

In [105]:
df.filter(
    items=[
        'student_name',
        'student_class'
    ]
)

                   student_name  student_class
0             ALLAN THIGA MAINA  NNP/EIT4/25J1
1        BERNAD NDIRANGU MWANGI  NNP/EIT4/25J1
2           ISAAC KANJA KABUCHU  NNP/EIT4/25J1
3             ISAAC KIHAGI BIRU  NNP/EIT4/25J1
4            JAMES MUGENDI MUGI  NNP/EIT4/25J1
...                         ...            ...
17562  PATRICK KARIUKI GACHOMBA       WFB424S1
17563         PETER MAINA WANJA  NNP/WFB4/25J1
17564     BENJAMIN  KIOKO  PAUL  NNP/WFB5/24S1
17565     DAVID MURIITHI ABWAVO  NNP/WFB5/24S1
17566            MICHAE CHEPTOO  NNP/WFB5/23S1

[17567 rows x 2 columns]

In [107]:
df.filter(
    like='grading'
)

,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score
0,10.0,38.6,NaN
1,20.0,51.4,15.0
2,NaN,NaN,NaN
3,20.0,60.0,20.0
4,20.0,42.9,16.7
...,...,...,...
17562,NaN,NaN,NaN
17563,NaN,NaN,NaN
17564,NaN,NaN,NaN
17565,NaN,NaN,NaN
17566,NaN,NaN,NaN

In [108]:
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [109]:
df.filter(regex='^a')

,attachment_period,attachment_start_date,attachment_end_date,assigned_manual
0,SEPT-DEC,2025-09-01,2025-12-31,ASSIGNED
1,SEPT-DEC,2025-09-01,2025-12-31,ASSIGNED
2,SEPT-DEC,2025-09-01,2025-12-31,ASSIGNED
3,SEPT-DEC,2025-09-01,2025-12-31,ASSIGNED
4,SEPT-DEC,2025-09-01,2025-12-31,ASSIGNED
...,...,...,...,...
17562,MAY - AUG,2025-05-01,2025-08-31,NOT ASSIGNED
17563,SEPT-DEC,2025-09-01,2025-12-31,NOT ASSIGNED
17564,JAN-APRIL,2026-01-01,2026-04-30,NOT ASSIGNED
17565,JAN-APRIL,2026-01-01,2026-04-30,NOT ASSIGNED
17566,MAY - AUG,2025-05-01,2025-08-31,NOT ASSIGNED

In [110]:
df.filter(regex='_date')

      attachment_start_date attachment_end_date
0                2025-09-01          2025-12-31
1                2025-09-01          2025-12-31
2                2025-09-01          2025-12-31
3                2025-09-01          2025-12-31
4                2025-09-01          2025-12-31
...                     ...                 ...
17562            2025-05-01          2025-08-31
17563            2025-09-01          2025-12-31
17564            2026-01-01          2026-04-30
17565            2026-01-01          2026-04-30
17566            2025-05-01          2025-08-31

[17567 rows x 2 columns]

In [111]:
df.filter(regex='grading')

,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score
0,10.0,38.6,NaN
1,20.0,51.4,15.0
2,NaN,NaN,NaN
3,20.0,60.0,20.0
4,20.0,42.9,16.7
...,...,...,...
17562,NaN,NaN,NaN
17563,NaN,NaN,NaN
17564,NaN,NaN,NaN
17565,NaN,NaN,NaN
17566,NaN,NaN,NaN

In [115]:
df.select_dtypes(include=['integer','string'])

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,company_name,sector_name,placement_status,graded,assigned_manual
0,ALLAN THIGA MAINA,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,54056,SEPT-DEC,2025,SAMTECH ELECTRICALS,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,NOT GRADED,ASSIGNED
1,BERNAD NDIRANGU MWANGI,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,51732,SEPT-DEC,2025,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, HEALTH CARE GIVER, HEALTHCARE...",PLACED,GRADED,ASSIGNED
2,ISAAC KANJA KABUCHU,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,53862,SEPT-DEC,2025,NYERI RURINGU,NaN,PLACED,NOT GRADED,ASSIGNED
3,ISAAC KIHAGI BIRU,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,51609,SEPT-DEC,2025,KENYA POWER NYERI,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,GRADED,ASSIGNED
4,JAMES MUGENDI MUGI,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,53842,SEPT-DEC,2025,ITUMBE TEA FACTORY CO LTD,ELECTRICAL & ELECTRONICS ENGINEERING,PLACED,GRADED,ASSIGNED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,PATRICK KARIUKI GACHOMBA,WFB424S1,WELDING AND FABRICATION LEVEL 4,1,NaN,CBS,50934,MAY - AUG,2025,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17563,PETER MAINA WANJA,NNP/WFB4/25J1,WELDING AND FABRICATION LEVEL 4,1,NaN,CBS,52158,SEPT-DEC,2025,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17564,BENJAMIN KIOKO PAUL,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1,NaN,CBS,51774,JAN-APRIL,2026,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17565,DAVID MURIITHI ABWAVO,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1,NaN,CBS,52027,JAN-APRIL,2026,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17566,MICHAE CHEPTOO,NNP/WFB5/23S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,<NA>,NaN,CBS,46017,MAY - AUG,2025,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED

In [117]:
df.drop(
    columns=['student_adm_no','student_class','student_name']
)

,student_course,student_year,student_gender,student_category,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,SEPT-DEC,2025,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,NOT GRADED,ASSIGNED,10.0,38.6,NaN,NaN
1,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,SEPT-DEC,2025,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, HEALTH CARE GIVER, HEALTHCARE...",PLACED,GRADED,ASSIGNED,20.0,51.4,15.0,86.0
2,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,SEPT-DEC,2025,2025-09-01,2025-12-31,NYERI RURINGU,NaN,PLACED,NOT GRADED,ASSIGNED,NaN,NaN,NaN,NaN
3,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,SEPT-DEC,2025,2025-09-01,2025-12-31,KENYA POWER NYERI,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,GRADED,ASSIGNED,20.0,60.0,20.0,100.0
4,ELECTRICAL INSTALLATION TECHNOLOGY,1,NaN,CBS,SEPT-DEC,2025,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,ELECTRICAL & ELECTRONICS ENGINEERING,PLACED,GRADED,ASSIGNED,20.0,42.9,16.7,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,WELDING AND FABRICATION LEVEL 4,1,NaN,CBS,MAY - AUG,2025,2025-05-01,2025-08-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17563,WELDING AND FABRICATION LEVEL 4,1,NaN,CBS,SEPT-DEC,2025,2025-09-01,2025-12-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17564,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1,NaN,CBS,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17565,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1,NaN,CBS,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN
17566,WELDING AND FABRICATION TECHNICIAN LEVEL 5,<NA>,NaN,CBS,MAY - AUG,2025,2025-05-01,2025-08-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED,NaN,NaN,NaN,NaN

In [119]:
df.drop(
    columns=df.filter(like='student').columns
)

,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual
0,SEPT-DEC,2025,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,NOT GRADED,ASSIGNED
1,SEPT-DEC,2025,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, HEALTH CARE GIVER, HEALTHCARE...",PLACED,GRADED,ASSIGNED
2,SEPT-DEC,2025,2025-09-01,2025-12-31,NYERI RURINGU,NaN,PLACED,NOT GRADED,ASSIGNED
3,SEPT-DEC,2025,2025-09-01,2025-12-31,KENYA POWER NYERI,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,GRADED,ASSIGNED
4,SEPT-DEC,2025,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,ELECTRICAL & ELECTRONICS ENGINEERING,PLACED,GRADED,ASSIGNED
...,...,...,...,...,...,...,...,...,...
17562,MAY - AUG,2025,2025-05-01,2025-08-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17563,SEPT-DEC,2025,2025-09-01,2025-12-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17564,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17565,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17566,MAY - AUG,2025,2025-05-01,2025-08-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED

In [121]:
df.drop(
    columns=df.filter(regex='^student_').columns
)

,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual
0,SEPT-DEC,2025,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,NOT GRADED,ASSIGNED
1,SEPT-DEC,2025,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, HEALTH CARE GIVER, HEALTHCARE...",PLACED,GRADED,ASSIGNED
2,SEPT-DEC,2025,2025-09-01,2025-12-31,NYERI RURINGU,NaN,PLACED,NOT GRADED,ASSIGNED
3,SEPT-DEC,2025,2025-09-01,2025-12-31,KENYA POWER NYERI,"ELECTRICAL & ELECTRONICS ENGINEERING, ELECTRIC...",PLACED,GRADED,ASSIGNED
4,SEPT-DEC,2025,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,ELECTRICAL & ELECTRONICS ENGINEERING,PLACED,GRADED,ASSIGNED
...,...,...,...,...,...,...,...,...,...
17562,MAY - AUG,2025,2025-05-01,2025-08-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17563,SEPT-DEC,2025,2025-09-01,2025-12-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17564,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17565,JAN-APRIL,2026,2026-01-01,2026-04-30,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED
17566,MAY - AUG,2025,2025-05-01,2025-08-31,NaN,NaN,NOT PLACED,NOT GRADED,NOT ASSIGNED

In [124]:
df.select_dtypes(exclude=['string','datetime','integer'])

,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,10.0,38.6,NaN,NaN
1,20.0,51.4,15.0,86.0
2,NaN,NaN,NaN,NaN
3,20.0,60.0,20.0,100.0
4,20.0,42.9,16.7,80.0
...,...,...,...,...
17562,NaN,NaN,NaN,NaN
17563,NaN,NaN,NaN,NaN
17564,NaN,NaN,NaN,NaN
17565,NaN,NaN,NaN,NaN
17566,NaN,NaN,NaN,NaN