In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [3]:
df=pd.read_excel('datasets/nyeri.xlsx')

In [6]:
df.head(1)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN

In [7]:
#CHECK DATATYPE OF THE DATASETS
df.dtypes

student_name                            object
student_class                              str
student_course                             str
student_year                           float64
student_gender                             str
student_category                           str
student_adm_no                          object
attachment_period                          str
year                                   float64
attachment_start_date                      str
attachment_end_date                        str
company_name                               str
sector_name                                str
placement_status                           str
graded                                     str
assigned_manual                            str
student_workbehaviour_grading_score    float64
student_skills_grading_score           float64
student_knowledge_grading_score        float64
student_final_score                    float64
dtype: object

In [9]:
df['student_name'].dtype

dtype('O')

In [10]:
df['year'].dtype

dtype('float64')

In [13]:
df['student_year']=pd.to_numeric(df['student_year'],errors='coerce')

In [14]:
df['student_year'].dtype

dtype('float64')

In [15]:
df['student_year']=df['student_year'].astype('Int64')

In [16]:
df['student_year'].dtype

Int64Dtype()

In [17]:
df.dtypes

student_name                            object
student_class                              str
student_course                             str
student_year                             Int64
student_gender                             str
student_category                           str
student_adm_no                          object
attachment_period                          str
year                                   float64
attachment_start_date                      str
attachment_end_date                        str
company_name                               str
sector_name                                str
placement_status                           str
graded                                     str
assigned_manual                            str
student_workbehaviour_grading_score    float64
student_skills_grading_score           float64
student_knowledge_grading_score        float64
student_final_score                    float64
dtype: object

In [18]:
df['student_year']=df['student_year'].astype(float)

In [19]:
df.dtypes

student_name                            object
student_class                              str
student_course                             str
student_year                           float64
student_gender                             str
student_category                           str
student_adm_no                          object
attachment_period                          str
year                                   float64
attachment_start_date                      str
attachment_end_date                        str
company_name                               str
sector_name                                str
placement_status                           str
graded                                     str
assigned_manual                            str
student_workbehaviour_grading_score    float64
student_skills_grading_score           float64
student_knowledge_grading_score        float64
student_final_score                    float64
dtype: object

In [20]:
#CONVERT TO STRING
df['year']=df['year'].astype(str)

In [21]:
df.dtypes

student_name                            object
student_class                              str
student_course                             str
student_year                           float64
student_gender                             str
student_category                           str
student_adm_no                          object
attachment_period                          str
year                                       str
attachment_start_date                      str
attachment_end_date                        str
company_name                               str
sector_name                                str
placement_status                           str
graded                                     str
assigned_manual                            str
student_workbehaviour_grading_score    float64
student_skills_grading_score           float64
student_knowledge_grading_score        float64
student_final_score                    float64
dtype: object

In [22]:
#CONVERT TO CETGORYCAL DATATYPE
df['student_gender']=df['student_gender'].astype('category')

In [23]:
df.dtypes

student_name                             object
student_class                               str
student_course                              str
student_year                            float64
student_gender                         category
student_category                            str
student_adm_no                           object
attachment_period                           str
year                                        str
attachment_start_date                       str
attachment_end_date                         str
company_name                                str
sector_name                                 str
placement_status                            str
graded                                      str
assigned_manual                             str
student_workbehaviour_grading_score     float64
student_skills_grading_score            float64
student_knowledge_grading_score         float64
student_final_score                     float64
dtype: object

In [24]:
df

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51732,sept-dec,2025.0,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53862,sept-dec,2025.0,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51609,sept-dec,2025.0,2025-09-01,2025-12-31,KENYA POWER NYERI,"Electrical & Electronics Engineering, Electric...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0
4,James Mugendi Mugi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53842,sept-dec,2025.0,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,Electrical & Electronics Engineering,Placed,Graded,Assigned,20.0,42.9,16.7,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,Patrick kariuki Gachomba,WFB424S1,WELDING AND FABRICATION LEVEL 4,1.0,Male,CBS,50934,May - Aug,2025.0,2025-05-01,2025-08-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17563,Peter Maina Wanja,NNP/WFB4/25J1,WELDING AND FABRICATION LEVEL 4,1.0,Male,CBS,52158,sept-dec,2025.0,2025-09-01,2025-12-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17564,Benjamin Kioko Paul,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1.0,Male,CBS,51774,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17565,David Muriithi Abwavo,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1.0,Male,CBS,52027,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17566,michae cheptoo,NNP/WFB5/23S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,NaN,Male,CBS,46017,May - Aug,2025.0,2025-05-01,2025-08-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN

In [25]:
df['grade_boolean']=df['graded'].map({
    'Not Graded':'False',
    'Graded':'True'
})

In [26]:
df

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,...,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score,grade_boolean
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,...,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN,False
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51732,sept-dec,2025.0,2025-09-01,...,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0,True
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53862,sept-dec,2025.0,2025-09-01,...,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN,False
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51609,sept-dec,2025.0,2025-09-01,...,KENYA POWER NYERI,"Electrical & Electronics Engineering, Electric...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0,True
4,James Mugendi Mugi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53842,sept-dec,2025.0,2025-09-01,...,ITUMBE TEA FACTORY CO LTD,Electrical & Electronics Engineering,Placed,Graded,Assigned,20.0,42.9,16.7,80.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,Patrick kariuki Gachomba,WFB424S1,WELDING AND FABRICATION LEVEL 4,1.0,Male,CBS,50934,May - Aug,2025.0,2025-05-01,...,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN,False
17563,Peter Maina Wanja,NNP/WFB4/25J1,WELDING AND FABRICATION LEVEL 4,1.0,Male,CBS,52158,sept-dec,2025.0,2025-09-01,...,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN,False
17564,Benjamin Kioko Paul,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1.0,Male,CBS,51774,jan-april,2026.0,2026-01-01,...,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN,False
17565,David Muriithi Abwavo,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1.0,Male,CBS,52027,jan-april,2026.0,2026-01-01,...,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN,False
17566,michae cheptoo,NNP/WFB5/23S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,NaN,Male,CBS,46017,May - Aug,2025.0,2025-05-01,...,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN,False

In [27]:
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score',
 'grade_boolean']

In [29]:
df.loc[:,['student_name','graded','grade_boolean']
]

                   student_name      graded grade_boolean
0             Allan Thiga Maina  Not Graded         False
1        Bernad Ndirangu Mwangi      Graded          True
2           Isaac Kanja Kabuchu  Not Graded         False
3             Isaac Kihagi Biru      Graded          True
4            James Mugendi Mugi      Graded          True
...                         ...         ...           ...
17562  Patrick kariuki Gachomba  Not Graded         False
17563         Peter Maina Wanja  Not Graded         False
17564     Benjamin  Kioko  Paul  Not Graded         False
17565     David Muriithi Abwavo  Not Graded         False
17566            michae cheptoo  Not Graded         False

[17567 rows x 3 columns]