In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [3]:
df=pd.read_excel('datasets/nyeri.xlsx')

In [5]:
df.columns

Index(['student_name', 'student_class', 'student_course', 'student_year',
       'student_gender', 'student_category', 'student_adm_no',
       'attachment_period', 'year', 'attachment_start_date',
       'attachment_end_date', 'company_name', 'sector_name',
       'placement_status', 'graded', 'assigned_manual',
       'student_workbehaviour_grading_score', 'student_skills_grading_score',
       'student_knowledge_grading_score', 'student_final_score'],
      dtype='str')

In [6]:
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: float64(6), object(2), str(12)
memory usage: 2.7+ MB

In [8]:
df.describe()

,student_year,year,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
count,10470.000000,15151.000000,7258.000000,8048.000000,7546.000000,6839.000000
mean,1.529131,2024.542340,17.611298,54.211767,17.401365,93.187601
std,0.627985,1.005549,5.447891,13.934138,5.441821,12.954791
min,1.000000,2023.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,2024.000000,18.500000,56.600000,18.200000,92.000000
50%,1.000000,2025.000000,20.000000,60.000000,20.000000,100.000000
75%,2.000000,2025.000000,20.000000,60.000000,20.000000,100.000000
max,6.000000,2026.000000,20.000000,106.800000,24.800000,135.000000

In [9]:
df.shape

(17567, 20)

In [10]:
df.isna().values.any()

np.True_

In [12]:
df.isnull().values.any()

np.True_

In [13]:
df.isna().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [14]:
df.isnull().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [15]:
df.isna().sum().sum()

np.int64(69605)

In [17]:
df.isnull().sum().sum()

np.int64(69605)

In [18]:
df['student_year'].isnull().sum()

np.int64(7097)

In [19]:
df['student_year'].isna().sum()

np.int64(7097)

In [20]:
df[df['student_year'].isnull()]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
108,judy nyakio gichira,NNP/CMT6/25M2,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...,NaN,Female,CBS,42115,Jan-April,2025.0,2025-01-01,2025-04-30,EUNICE BEAUTY SALON,Cosmetology,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
109,judy nyakio gichira,NNP/CMT6/25M2,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...,NaN,Female,CBS,42115,January - April,2024.0,2024-01-01,2024-04-30,JANELLE SALON,"BEAUTY, Cosmetology, Hair Dressing",Placed,Not Graded,Assigned,NaN,60.0,20.0,NaN
114,Wanjiru Kinuthia Talia,NNP/FDM4/24M1,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...,NaN,Female,CBS,42688,January - April,2024.0,2024-01-01,2024-04-30,EMPOLOS HOTEL,"Accommodation Operations, Catering and accommo...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0
143,Jesse Mwangi Kimondo,MVM424M1,ARTISAN MOTOR VEHICLE MECHANICS -YEAR 1,NaN,Male,CBS,43870,MAY - JULY,2024.0,2024-05-01,2024-08-25,AUTOSPIN GARAGE LTD,"Automotive & Electronics Engineering, AUTOMOTI...",Placed,Graded,Assigned,0.0,60.0,20.0,80.0
144,Jesse Mwangi Kimondo,MVM424M1,ARTISAN MOTOR VEHICLE MECHANICS -YEAR 1,NaN,Male,CBS,43870,MAY - JULY,2024.0,2024-05-01,2024-08-25,AUTOSPIN GARAGE LTD,"Automotive & Electronics Engineering, AUTOMOTI...",Placed,Graded,Assigned,0.0,60.0,20.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17535,STUDENT 4 SEL6,SEL6/024/M\t,Software Engineering Level 6,NaN,Female,CBET,SEL64,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17551,Chrisjohn Githaiga Maina,\t\tNNP/WFB4/24M1,WELDING AND FABRICATION LEVEL 4,NaN,Male,CBS,48549,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17555,Karimi Wanja Kenneth,\t\tNNP/WFB4/24M1,WELDING AND FABRICATION LEVEL 4,NaN,Male,CBS,49517,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17561,Nahason Kihia Wangombe,\t\tNNP/WFB4/24M1,WELDING AND FABRICATION LEVEL 4,NaN,Male,CBS,46319,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17566,michae cheptoo,NNP/WFB5/23S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,NaN,Male,CBS,46017,May - Aug,2025.0,2025-05-01,2025-08-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN

In [23]:
student_missing_student_year=df.loc[
    df['student_year'].isnull(),
    ['student_name','student_class','student_course','student_category']
    ]

In [24]:
student_missing_student_year.to_excel('datasets/student_missing_student_year.xlsx',index=False)

In [26]:
os.path.exists('datasets/student_missing_student_year.xlsx')

True

In [27]:
df[
    df['student_year'].isnull() &
    df['attachment_period'].isnull()
]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
12295,Irene wairimu Mithamo,Alumni,NaN,NaN,Female,KNEC,36159,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
12302,maurice john ikonze,NNP/AGE6/26M-M1,AGRICULTURAL EXTENSION LEVEL 6,NaN,Male,CBS,60641,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
12439,Allan Macharia Kamau,Alumni,AUTOMOTIVE ENGINEERING TECHNICIAN LEVEL 5,NaN,Male,KNEC,37633,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
12576,FRANKLIN MUTUA MUTUKU,AMC6/23S1,AUTOMOTIVE TECHNICIAN LEVEL 6,NaN,Male,CBS,44605,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
12594,Joan Wanjiru Wanjiru,NNP/BRS3/26M1,BARISTA SKILLS LEVEL 3,NaN,Male,CBET,60957,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17480,36159,\tNNP/SLT6/24M2,SCIENCE LABORATORY TECHNICIAN LEVEL 6,NaN,Female,CBS,Irene Wairimu Mithamo,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17532,STUDENT 1 SEL6,SEL6/024/M\t,Software Engineering Level 6,NaN,Female,CBET,SEL61,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17533,STUDENT 2 SEL6,SEL6/024/M\t,Software Engineering Level 6,NaN,Female,CBET,SEL62,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17534,STUDENT 3 SEL6,SEL6/024/M\t,Software Engineering Level 6,NaN,Female,CBET,SEL63,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17535,STUDENT 4 SEL6,SEL6/024/M\t,Software Engineering Level 6,NaN,Female,CBET,SEL64,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN

In [32]:
df.loc[
    #df['student_year'].isnull(), 
    df['attachment_period'].isnull(),
    ['student_name','student_class','student_category','student_year']
]

                student_name    student_class student_category  student_year
12295  Irene wairimu Mithamo           Alumni             KNEC           NaN
12302    maurice john ikonze  NNP/AGE6/26M-M1              CBS           NaN
12439   Allan Macharia Kamau           Alumni             KNEC           NaN
12576  FRANKLIN MUTUA MUTUKU        AMC6/23S1              CBS           NaN
12594   Joan Wanjiru Wanjiru    NNP/BRS3/26M1             CBET           NaN
...                      ...              ...              ...           ...
17480                  36159  \tNNP/SLT6/24M2              CBS           NaN
17532         STUDENT 1 SEL6     SEL6/024/M\t             CBET           NaN
17533         STUDENT 2 SEL6     SEL6/024/M\t             CBET           NaN
17534         STUDENT 3 SEL6     SEL6/024/M\t             CBET           NaN
17535         STUDENT 4 SEL6     SEL6/024/M\t             CBET           NaN

[2416 rows x 4 columns]

In [33]:
df[
    df.isnull().all(axis=1)
]

Empty DataFrame
Columns: [student_name, student_class, student_course, student_year, student_gender, student_category, student_adm_no, attachment_period, year, attachment_start_date, attachment_end_date, company_name, sector_name, placement_status, graded, assigned_manual, student_workbehaviour_grading_score, student_skills_grading_score, student_knowledge_grading_score, student_final_score]
Index: []

In [34]:
df.isnull().all(axis=1).sum()

np.int64(0)

In [35]:
df[
    df.isnull().any(axis=1)
]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53862,sept-dec,2025.0,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
10,Michael Odhiambo Owino,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51805,sept-dec,2025.0,2025-09-01,2025-12-31,EDU TECH,Electrical Engineering (Power option),Placed,Not Graded,Assigned,NaN,51.4,NaN,NaN
11,Mwangi Wambugu Fredrick,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,24252,sept-dec,2025.0,2025-09-01,2025-12-31,COUNTY GOVERNMENT OF LAIKIPIA - DIVISION OF LA...,Electrical & Electronics Engineering,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
14,Ndungi Tobias Bachia,NNP/EIT3/26J-J1,MODULARIZED ELECTRICAL INSTALLATION TECHNOLOG...,1.0,Male,CBS,59097,may-aug,2026.0,2026-05-01,2026-08-31,GATHUTHI TEA FACTORY,"ACCOUNTS, Automotive sector , HUMAN RESOURCE M...",Placed,Not Graded,Assigned,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,Patrick kariuki Gachomba,WFB424S1,WELDING AND FABRICATION LEVEL 4,1.0,Male,CBS,50934,May - Aug,2025.0,2025-05-01,2025-08-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17563,Peter Maina Wanja,NNP/WFB4/25J1,WELDING AND FABRICATION LEVEL 4,1.0,Male,CBS,52158,sept-dec,2025.0,2025-09-01,2025-12-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17564,Benjamin Kioko Paul,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1.0,Male,CBS,51774,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17565,David Muriithi Abwavo,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,1.0,Male,CBS,52027,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17566,michae cheptoo,NNP/WFB5/23S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,NaN,Male,CBS,46017,May - Aug,2025.0,2025-05-01,2025-08-31,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN

In [36]:
df.isnull().any(axis=1).sum()

np.int64(13569)

In [37]:
df.isnull().any().sum()

np.int64(13)

In [38]:
df.columns[
    df.isnull().any()
]

Index(['student_course', 'student_year', 'student_gender', 'attachment_period',
       'year', 'attachment_start_date', 'attachment_end_date', 'company_name',
       'sector_name', 'student_workbehaviour_grading_score',
       'student_skills_grading_score', 'student_knowledge_grading_score',
       'student_final_score'],
      dtype='str')

In [40]:
list(
    df.columns[
        df.isnull().any()
    ]
)

['student_course',
 'student_year',
 'student_gender',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [42]:
list(
    df.columns[
        ~df.isnull().any()
    ]
)

['student_name',
 'student_class',
 'student_category',
 'student_adm_no',
 'placement_status',
 'graded',
 'assigned_manual']

In [43]:
df.isnull().sum().sum()

np.int64(69605)

In [50]:
df.shape

(17567, 20)

In [47]:
no_missing_values=df.dropna()

In [49]:
no_missing_values.shape

(3998, 20)