In [1]:
#IMPORT THE NECESSARY PACKAGES
import pandas as pd
import os

In [2]:
#GETTING WORKING DIRECTORY
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [3]:
df=pd.read_excel("datasets/nyeri.xlsx")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: float64(6), object(2), str(12)
memory usage: 2.7+ MB

In [5]:
#DATA CLEANING
    #1.0 CONVERTING attachment_start_date and attachment_end_date to date format
df['attachment_start_date']=pd.to_datetime(df['attachment_start_date'],errors='coerce')
df['attachment_end_date']=pd.to_datetime(df['attachment_end_date'],errors='coerce')
df['year']=df['year'].astype('Int64')
df['student_year']=pd.to_numeric(df['student_year'],errors='coerce').astype('Int64')

df['student_adm_no']=pd.to_numeric(df['student_adm_no'],errors='coerce').astype('Int64')
df['student_name']=df['student_name'].astype('string')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  string
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  Int64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17479 non-null  Int64
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  Int64
 9   attachment_start_date                15151 non-null  datetime64[us]
 10  attachment_end_date                  15151 non-null  datetime64[us]
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: Int64(3), datetime64[us](2), float64(4), str(10), string(1)
memory usage: 2.7 MB

In [289]:
df['student_gender'].dropna().unique()

<StringArray>
[   'Male',  'Female',       'F',    'MALE',  'FEMALE',  'female',       'M',
    'male',  'FEMale',   'Male ',  'FeMale', 'FE4MALE']
Length: 12, dtype: str

In [ ]:
string_columns=df.select_dtypes(include=['string','object']).columns
df[string_columns]=df[string_columns].apply(
    lambda col:col.str.strip().str.upper()
)

In [290]:
df['student_gender']=df['student_gender'].str.strip().str.upper()

In [291]:
df['student_gender'].dropna().unique()

<StringArray>
['MALE', 'FEMALE', 'F', 'M', 'FE4MALE']
Length: 5, dtype: str

In [292]:
df['student_gender']=df['student_gender'].replace({
    'MALE':'MALE',
    'M':'MALE',
    'FEMALE':'FEMALE',
    'F':'FEMALE',
    'FE4MALE':'FEMALE'
})

In [293]:
df['student_gender'].dropna().unique()

<StringArray>
['MALE', 'FEMALE']
Length: 2, dtype: str

In [294]:
df['attachment_period'].dropna().unique()

<StringArray>
[             'sept-dec',      'January -  April',               'may-aug',
             'May - Aug',             'Jan-April',             'Sep - Dec',
             'jan-april',            'Sept - Nov',            'MAY - JULY',
        'jan-april dual',         'SEPT-DEC dual',        'DUAL SEP - NOV',
 'may-aug dual training',          'may-aug dual',        'JAN-APRIL DUAL',
             'Nov - Dec',       'August-November',               'AUG-DEC',
        'May Attachment',   'pharmacy april-june',      'AUG-OCT PHARMACY',
     'PHARMACY JULY-AUG',        'JAN-APRIL 2026']
Length: 23, dtype: str

In [295]:
#STANDARDIZING ATTACHMENT PERIOD COLUMN
df['attachment_period']=df['attachment_period'].str.strip().str.upper()

In [296]:
df['attachment_period'].dropna().unique()

<StringArray>
[             'SEPT-DEC',      'JANUARY -  APRIL',               'MAY-AUG',
             'MAY - AUG',             'JAN-APRIL',             'SEP - DEC',
            'SEPT - NOV',            'MAY - JULY',        'JAN-APRIL DUAL',
         'SEPT-DEC DUAL',        'DUAL SEP - NOV', 'MAY-AUG DUAL TRAINING',
          'MAY-AUG DUAL',             'NOV - DEC',       'AUGUST-NOVEMBER',
               'AUG-DEC',        'MAY ATTACHMENT',   'PHARMACY APRIL-JUNE',
      'AUG-OCT PHARMACY',     'PHARMACY JULY-AUG',        'JAN-APRIL 2026']
Length: 21, dtype: str

In [297]:
#REPLACING ATTACHMENT PERIOD VALUES
df['attachment_period']=df['attachment_period'].replace({
    'JAN-APRIL':'JAN-APR',
    'JANUARY -  APRIL':'JAN-APR',
    'JAN-APRIL DUAL':'JAN-APR',
    'PHARMACY APRIL-JUNE':'APR-JUN',
    'MAY - JULY':'MAY-JUL',
    'MAY - AUG':'MAY-AUG',
    'MAY-AUG DUAL TRAINING':'MAY-AUG',
    'PHARMACY JULY-AUG':'JUL-AUG',
    'SEPT - NOV':'SEP-NOV',
    'DUAL SEP - NOV':'SEP-NOV',
    'SEPT-DEC':'SEP-DEC',
    'SEPT-DEC DUAL':'SEP-DEC',
    'SEP - DEC':'SEP-DEC' ,
    'AUGUST-NOVEMBER':'AUG-NOV',
    'NOV - DEC':'NOV-DEC'
})

In [298]:
df['attachment_period'].dropna().unique()

<StringArray>
[         'SEP-DEC',          'JAN-APR',          'MAY-AUG',
          'SEP-NOV',          'MAY-JUL',     'MAY-AUG DUAL',
          'NOV-DEC',          'AUG-NOV',          'AUG-DEC',
   'MAY ATTACHMENT',          'APR-JUN', 'AUG-OCT PHARMACY',
          'JUL-AUG',   'JAN-APRIL 2026']
Length: 14, dtype: str

In [299]:
string_columns=df.select_dtypes(include=['string','object']).columns
df[string_columns]=df[string_columns].apply(
    lambda col:col.str.strip().str.upper()
)

In [300]:
df = df[df['student_class'] != 'ALUMNI']

In [301]:
df=df[df['student_class'] !='SEL6/024/M']

In [302]:
df['attachment_start_day']=df['attachment_start_date'].dt.day.astype('Int64')
df['attachment_start_month']=df['attachment_start_date'].dt.strftime('%b')
df['attachment_start_year']=df['attachment_start_date'].dt.year.astype('Int64')

df['attachment_end_day']=df['attachment_end_date'].dt.day.astype('Int64')
df['attachment_end_month']=df['attachment_end_date'].dt.strftime('%b')
df['attachment_end_year']=df['attachment_end_date'].dt.year.astype('Int64')

In [303]:
#CAPITALIZE THE ATTACHMENT START MONTH AND ATTACHMENT END MONTH
df['attachment_start_month']=df['attachment_start_month'].str.strip().str.upper()
df['attachment_end_month']=df['attachment_end_month'].str.strip().str.upper()

In [304]:
#CONCATENATE ATTACHMENT START_MONTH AND ATTACHMENT END MONTH
df['attachment_period_2']=(df['attachment_start_month'] + '-'+ df['attachment_end_month'])

In [305]:
df[[
    'attachment_start_date',
    'attachment_start_day',
    'attachment_start_month',
    'attachment_start_year',
    'attachment_end_day',
    'attachment_end_month',
    'attachment_end_year',
    'attachment_period_2'
]].head(3)

,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_end_day,attachment_end_month,attachment_end_year,attachment_period_2
0,2025-09-01,1,SEP,2025,31,DEC,2025,SEP-DEC
1,2025-09-01,1,SEP,2025,31,DEC,2025,SEP-DEC
2,2025-09-01,1,SEP,2025,31,DEC,2025,SEP-DEC

In [306]:
df.loc[
    df['attachment_period'].notna() &
    df['attachment_period_2'].notna() &
    (df['attachment_period'] != df['attachment_period_2']),
    ['attachment_period', 'attachment_period_2']
]

      attachment_period attachment_period_2
143             MAY-JUL             MAY-AUG
144             MAY-JUL             MAY-AUG
234        MAY-AUG DUAL             MAY-AUG
240             MAY-JUL             MAY-AUG
245             MAY-JUL             MAY-AUG
...                 ...                 ...
17216    MAY ATTACHMENT             MAY-AUG
17531           AUG-NOV             SEP-DEC
17544           AUG-NOV             SEP-DEC
17545           AUG-NOV             SEP-DEC
17549           AUG-NOV             SEP-DEC

[1399 rows x 2 columns]

In [307]:
df['placement_status'].value_counts()

placement_status
PLACED        12294
NOT PLACED     5265
Name: count, dtype: int64

In [308]:
#finding duplicates
columns=['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score',
 'attachment_start_day',
 'attachment_start_month',
 'attachment_start_year',
 'attachment_end_day',
 'attachment_end_month',
 'attachment_end_year',
 'attachment_period_2']
#duplicates=df.duplicated(subset=columns).sum()
duplicates=df[df.duplicated(subset=columns,keep=False)]
len(duplicates)

466

In [309]:
len(df)

17559

In [310]:
#Keep Distinct values
cleaned_dataset_no_duplicates=df.drop_duplicates(subset=columns,keep='first')
cleaned_dataset_no_duplicates.to_excel('datasets/nyeri_cleaned_dataset_no_duplicates.xlsx',index=False)

In [311]:
duplicates.to_excel('datasets/nyeri_duplicates.xlsx',index=False)

In [312]:
##COUNTING CLASSES AN TOTAL NUMBER OF STUDENT
student_counts=df.dropna(
    subset=['attachment_period_2',
            'attachment_start_year',
            'attachment_end_year']).groupby([
                                    'student_class',
                                    'student_year',
                                    'student_course',
                                    'attachment_period_2',
                                    'attachment_start_year',
                                    'attachment_end_year'
]).size().reset_index(name='student_count')

In [313]:
duplicates_attachment_clases=student_counts[
    ~student_counts.duplicated(
    subset=['student_class',
            'student_course',
            'student_year'],keep=False)]

In [314]:
#SAVE DUPLICATES CLASES
duplicates_attachment_clases.to_excel('datasets/duplicate_attachment_clases.xlsx',index=False)

In [315]:
class_details = duplicates_attachment_clases[
    [
        'student_class',
        'student_course',
        'student_year',
        'attachment_start_year',
         'attachment_end_year',
        'attachment_period_2'
    ]
].copy()

In [316]:
class_details = class_details.rename(
    columns={
        'student_year': 'class_student_year',
        'attachment_end_year': 'class_attachment_end_year',
        'attachment_start_year': 'class_attachment_start_year',
        'attachment_period_2': 'class_attachment_period_2'
    }
)

In [317]:
df = df.merge(
    class_details,
    on=['student_class', 'student_course'],
    how='left'
)

In [318]:
df['student_year'] = df['student_year'].fillna(
    df['class_student_year']
)

In [319]:
df['attachment_start_year'] = df['attachment_start_year'].fillna(
    df['class_attachment_start_year']
)

In [320]:
df['attachment_end_year'] = df['attachment_end_year'].fillna(
    df['class_attachment_end_year']
)

In [321]:
df['attachment_period_2'] = df['attachment_period_2'].fillna(
    df['class_attachment_period_2']
)

In [322]:
df['attachment_period_2'].isna().value_counts()

attachment_period_2
False    15442
True      2407
Name: count, dtype: int64

In [324]:
missing_attachment=df.loc[df['attachment_period_2'].isna(),[
    'student_name','student_admn_no','student_class','student_course','student_year','attachment_period_2'
]]

KeyError: "['student_admn_no'] not in index"

In [ ]:
missing_attachment.to_excel('datasets/missing_attachments.xlsx')

In [ ]:
#FINDING UNIQUE CLASSES
missing_attachment['student_class'].nunique()

In [ ]:
missing_attachment['student_name'].duplicated().sum()