In [1]:
#IMPORT PANDAS AND OS
import pandas as pd
import os

In [5]:
#GET CURRENT WORKING DIRECTORY
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [8]:
#IMPORT THE DATASET
df=pd.read_excel('datasets/nyeri.xlsx')
df.head(3)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51732,sept-dec,2025.0,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53862,sept-dec,2025.0,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN

In [9]:
#GETTING COLUMN NAMES
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [11]:
filtered_students=df.loc[
    df['student_final_score'].notna(),
    ['student_name','student_class','student_course','student_gender','student_final_score']
]

filtered_students.head(20)

,student_name,student_class,student_course,student_gender,student_final_score
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,86.0
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,100.0
4,James Mugendi Mugi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,80.0
5,Jimmy Gitonga Mwendwa,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,100.0
6,Kimani Mutugu Evan,NNP/EIT4/23M1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,80.0
7,Macharia Wainaina Maxwell,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,100.0
8,Michael Kigano,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,100.0
9,Michael Ngugi Kariuki,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,100.0
12,Peter Gichuru Kariuki,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,82.0
13,Roy Kiragu Githu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,56.0
15,ABIGAEL Wambui Kinyanjui,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Female,100.0
16,BENEDETA MUTHEU,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Female,100.0
17,BILAL IDDY,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Male,100.0
18,BLESSINGS MWENDE,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Female,100.0
19,David Maraka,AGS6/24M1,AGRICULTURAL EXTENSION LEVEL 6,Male,100.0
20,DENNIS MBAI,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Male,100.0
21,EDWIN GITU NDUHIU,AGS6/24J1,AGRICULTURAL EXTENSION LEVEL 6,Male,98.0
22,ESTHER WAIRIMU Waweru,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Female,100.0
23,Evans Waiganjo,NNP/AGS6/23S1,AGRICULTURAL EXTENSION LEVEL 6,Male,98.0
24,FABIAN LELELIT,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Male,100.0

In [12]:
#SORT BY ONE COLUMN
#SORT BY STUDENTS FINAL SCORE
filtered_students.sort_values(by='student_final_score')##SORT VALUES FROM ASCENDING

,student_name,student_class,student_course,student_gender,student_final_score
9337,Wangari Kariuki Yvonne,CDACC/HRM6/25J2,HUMAN RESOURCE MANAGER level 6,Female,1.0
8314,Levis Karanja Kamau,NNP/FDM6/25S2,FASHION DESIGN TECHNICIAN LEVEL 6,Male,1.0
3694,ONESMUS MUHORO GITAU,NNP/CVE6/24S1,CIVIL ENGINEERING TECHNOLOGY LEVEL 6 - NNP,Male,3.0
7504,Maina Muriithi Ephraim,NNP/EEP6/22J3,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,3.0
10931,Erick Mawira Kirimi,MVM425S2M,MOTOR VEHICLE MECHANICS LEVEL 4,Male,3.0
...,...,...,...,...,...
12160,Francis Lentiyani,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Male,126.0
12166,Lepuyapui Omollo,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Male,126.0
12176,Rose Lekochere,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Female,127.0
12178,Tanni Lekalkuli Delta,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Female,127.0
12146,Agnes Gathoni Waithera,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Female,135.0

In [14]:
#SORT FROM DESCENDING
filtered_students.sort_values(
    by='student_final_score',
    ascending=False
)

,student_name,student_class,student_course,student_gender,student_final_score
12146,Agnes Gathoni Waithera,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Female,135.0
12176,Rose Lekochere,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Female,127.0
12178,Tanni Lekalkuli Delta,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Female,127.0
12166,Lepuyapui Omollo,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Male,126.0
12160,Francis Lentiyani,nnp/tgd5/24s1,TOUR GUIDE LEVEL 5 - NNP,Male,126.0
...,...,...,...,...,...
7504,Maina Muriithi Ephraim,NNP/EEP6/22J3,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,3.0
10931,Erick Mawira Kirimi,MVM425S2M,MOTOR VEHICLE MECHANICS LEVEL 4,Male,3.0
3694,ONESMUS MUHORO GITAU,NNP/CVE6/24S1,CIVIL ENGINEERING TECHNOLOGY LEVEL 6 - NNP,Male,3.0
8314,Levis Karanja Kamau,NNP/FDM6/25S2,FASHION DESIGN TECHNICIAN LEVEL 6,Male,1.0
9337,Wangari Kariuki Yvonne,CDACC/HRM6/25J2,HUMAN RESOURCE MANAGER level 6,Female,1.0

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: float64(6), object(2), str(12)
memory usage: 2.7+ MB

In [16]:
df['student_year']=df['student_year'].astype('Int64')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  Int64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: Int64(1), float64(5), object(2), str(12)
memory usage: 2.7+ MB

In [18]:
df['year']=df['year'].astype('Int64')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  Int64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  Int64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: Int64(2), float64(4), object(2), str(12)
memory usage: 2.7+ MB

In [24]:
filtered_student_2=df.loc[
    df['student_final_score'].notna() & df['student_year'].notna() & df['year'].notna(),
    ['student_name','student_class','student_course','student_gender','student_year','year','student_final_score']
]

filtered_student_2

,student_name,student_class,student_course,student_gender,student_year,year,student_final_score
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,1,2025,86.0
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,1,2025,100.0
4,James Mugendi Mugi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,1,2025,80.0
5,Jimmy Gitonga Mwendwa,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,1,2025,100.0
6,Kimani Mutugu Evan,NNP/EIT4/23M1,ELECTRICAL INSTALLATION TECHNOLOGY,Male,1,2024,80.0
...,...,...,...,...,...,...,...
12286,Eliel Mwangi Mathenge,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,Male,1,2026,99.0
12289,Gitahi Nganga Patrick,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,Male,1,2025,100.0
12290,MICHAEL KIAMA ERICK,NNP/WFB5/23S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,MALE,1,2024,97.0
12291,michael mugumo kamwaro,nnp/wfb5/25j2,WELDING AND FABRICATION TECHNICIAN LEVEL 5,Male,2,2025,99.0
12294,Victor Njuguna Mwaura,NNP/WFB5/24S1,WELDING AND FABRICATION TECHNICIAN LEVEL 5,Male,1,2025,100.0

In [25]:
filtered_student_2.sort_values(
    by='student_year',
    ascending=False
)

,student_name,student_class,student_course,student_gender,student_year,year,student_final_score
7601,Nathan Ndaru Mugo,NNP/EEP6/26J2D,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,6,2026,100.0
7142,Austine Omondi Ouma,NNP/EEP6/26J2D,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,6,2026,80.0
7387,JOSEPH mugoiyo kanyiri,NNP/EEP6/26J2D,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,6,2026,80.0
7558,Muriithi Muchoki Peter,NNP/EEP6/26J2D,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,6,2026,80.0
7580,Mwangi Muturi Simon,NNP/EEP6/25J1D,ELECTRICAL TECHNICIAN (POWER OPTION) LEVEL 6,Male,4,2026,83.0
...,...,...,...,...,...,...,...
12257,Eva wanjiru,NNP/WET6/24S1,WATER ENGINEERING LEVEL 6,FeMale,1,2025,93.0
12256,Esther Njeri Karanja,NNP/WET6/24S1,WATER ENGINEERING LEVEL 6,Female,1,2025,100.0
22,ESTHER WAIRIMU Waweru,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Female,1,2025,100.0
21,EDWIN GITU NDUHIU,AGS6/24J1,AGRICULTURAL EXTENSION LEVEL 6,Male,1,2025,98.0
20,DENNIS MBAI,CDACC/AGS6/24S1,AGRICULTURAL EXTENSION LEVEL 6,Male,1,2025,100.0

In [27]:
filtered_student_2.sort_values(
    by='student_gender',
    ascending=False
)

,student_name,student_class,student_course,student_gender,student_year,year,student_final_score
10872,Daris Maina,nnp/mve4/25s-j2,MOTOR VEHICLE ELECTRICIAN LEVEL 4,male,1,2026,100.0
10519,Kamau Njuguna Mark,NNP/MPT6/23J1,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,male,1,2024,86.0
10945,NDUNGU WAHOME PAUL,MVM423S1,MOTOR VEHICLE MECHANICS LEVEL 4,male,1,2024,77.0
10946,NJOROGE NJENGA THOMAS,MVM423S1,MOTOR VEHICLE MECHANICS LEVEL 4,male,1,2024,80.0
12252,Benjamin maina,NNP/WET6/24S1,WATER ENGINEERING LEVEL 6,male,1,2025,100.0
...,...,...,...,...,...,...,...
9279,LENSON KIMANTHI,NNP/HRM5/23S1,HUMAN RESOURCE MANAGER level 5,NaN,1,2024,88.0
10536,Kiranga Mwangi Wachira,NNPMPT6/24J3,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,NaN,3,2024,100.0
10537,Kiranga Mwangi Wachira,NNPMPT6/24J3,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,NaN,3,2023,99.0
10607,Victor Nduati Mathenge,NNPMPT6/24J3,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,NaN,3,2023,95.0
11552,Josephine Wanza Kivya,NNP/SLT5/23S1,SCIENCE LABORATORY TECHNICIAN LEVEL 5,NaN,1,2024,95.0

In [28]:
#SORT BY TWO OR MORE COLUMS
filtered_student_2.sort_values(
    by=['student_gender','student_year']
)

,student_name,student_class,student_course,student_gender,student_year,year,student_final_score
8144,Wairimu Maina Felister,NNP/FDM5/22J2,FASHION DESIGN OPERATOR LEVEL 5,F,2,2023,31.0
9276,DIRAMU Guyo Hadija,NNP/HRM5/23S1,HUMAN RESOURCE MANAGER level 5,FEMALE,1,2024,100.0
9277,FIDERINE NTINYARI,NNP/HRM5/23S1,HUMAN RESOURCE MANAGER level 5,FEMALE,1,2024,95.0
9285,NJERI MBUTHIA BEATRICE,NNP/HRM5/23S1,HUMAN RESOURCE MANAGER level 5,FEMALE,1,2024,96.0
9286,SYLVIA KANANU,NNP/HRM5/23S1,HUMAN RESOURCE MANAGER level 5,FEMALE,1,2024,100.0
...,...,...,...,...,...,...,...
8987,Hannah Nyokabi Kabue,NNP/FTT5/25J2,FOOD TECHNOLOGY TECHNICAN LEVEL 5,NaN,2,2025,90.0
9001,Monica Wanjiku Wangari,NNP/FTT5/25J2,FOOD TECHNOLOGY TECHNICAN LEVEL 5,NaN,2,2025,100.0
10536,Kiranga Mwangi Wachira,NNPMPT6/24J3,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,NaN,3,2024,100.0
10537,Kiranga Mwangi Wachira,NNPMPT6/24J3,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,NaN,3,2023,99.0
10607,Victor Nduati Mathenge,NNPMPT6/24J3,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,NaN,3,2023,95.0

In [32]:
##SORT BY TWO COLUMNS WITH DIFFERENT SORTING DIRECTIONS
filtered_student_2.sort_values(
    by=['student_gender','student_final_score'],
    ascending=[True,False]
)

,student_name,student_class,student_course,student_gender,student_year,year,student_final_score
8144,Wairimu Maina Felister,NNP/FDM5/22J2,FASHION DESIGN OPERATOR LEVEL 5,F,2,2023,31.0
3970,Brenda Nyokabi,NNP/CMT5/25M2,COSMETOLOGIST LEVEL 5,FEMALE,2,2026,100.0
4062,Njeri Wambugu Christine,NNP/CMT5/25M2,COSMETOLOGIST LEVEL 5,FEMALE,2,2026,100.0
4087,Wambui Annah Mwangi,NNP/CMT5/25M2,COSMETOLOGIST LEVEL 5,FEMALE,2,2026,100.0
4093,Wambui Kinyua Faithirene,NNP/CMT5/25M2,COSMETOLOGIST LEVEL 5,FEMALE,2,2026,100.0
...,...,...,...,...,...,...,...
8126,Sharon Mumbi Chege,NNP/fdm5/24s1,FASHION DESIGN OPERATOR LEVEL 5,NaN,1,2025,72.0
4210,Wanjira Nduta Rebecca,NNP/cmt6/24s2,COSMETOLOGIST LEVEL 6,NaN,2,2025,64.0
8036,Maryanne Njambi,NNP/fdm5/24s1,FASHION DESIGN OPERATOR LEVEL 5,NaN,1,2025,61.0
4138,Jackline Waithira Njeru,NNP/cmt6/24s2,COSMETOLOGIST LEVEL 6,NaN,2,2025,55.0
8156,Wamuyu Mwangi Karen,NNP/fdm5/24s1,FASHION DESIGN OPERATOR LEVEL 5,NaN,1,2025,53.0

In [40]:
#FILTERING AND SORTING
df[
    df['placement_status']=='Placed'
].sort_values(
    by=['student_gender','student_final_score'],
    ascending=[False,True]
).head(5)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
10945,NDUNGU WAHOME PAUL,MVM423S1,MOTOR VEHICLE MECHANICS LEVEL 4,1,male,CBS,43689,MAY - JULY,2024,2024-05-01,2024-08-25,ITARA MOTOR GARAGE,"Automotive & Electronics Engineering, Automoti...",Placed,Graded,Assigned,0.0,57.1,20.0,77.0
10923,CHEGE NDUNGU SIMON,MVM423S1,MOTOR VEHICLE MECHANICS LEVEL 4,1,male,CBS,44595,MAY - JULY,2024,2024-05-01,2024-08-25,BOCH AUTO NAIVASHA,NaN,Placed,Graded,Assigned,0.0,60.0,20.0,80.0
10946,NJOROGE NJENGA THOMAS,MVM423S1,MOTOR VEHICLE MECHANICS LEVEL 4,1,male,CBS,44026,MAY - JULY,2024,2024-05-01,2024-08-25,RIGATIO AUTO GARAGE,"Automotive & Electronics Engineering, Automoti...",Placed,Graded,Assigned,0.0,60.0,20.0,80.0
12260,Joseph Kamau,NNP/WET6/24S1,WATER ENGINEERING LEVEL 6,1,male,CBS,49888,sept-dec,2025,2025-09-01,2025-12-31,NYERI WATER AND SANITATION COMPANY,"ICT Technician, Plumber, Records Clerk",Placed,Graded,Assigned,20.0,42.9,20.0,83.0
10519,Kamau Njuguna Mark,NNP/MPT6/23J1,MECHANICAL PRODUCTION TECHNICIAN LEVEL 6,1,male,CBS,41298,January - April,2024,2024-01-01,2024-04-30,GACHUHI ENGINEERING COMPANY,"Automotive & Electronics Engineering, AUTOMOTI...",Placed,Graded,Assigned,15.4,54.5,16.0,86.0

In [48]:
df.loc[
    (df['placement_status']=='Placed') & df['student_final_score'].notna(),
    ['student_name','student_gender','student_final_score']
].sort_values(
    by=['student_final_score','student_gender'],
    ascending=[False,False]
)

                 student_name student_gender  student_final_score
12146  Agnes Gathoni Waithera         Female                135.0
12176          Rose Lekochere         Female                127.0
12178   Tanni Lekalkuli Delta         Female                127.0
12160       Francis Lentiyani           Male                126.0
12166        Lepuyapui Omollo           Male                126.0
...                       ...            ...                  ...
3694     ONESMUS MUHORO GITAU           Male                  3.0
7504   Maina Muriithi Ephraim           Male                  3.0
10931     Erick Mawira Kirimi           Male                  3.0
8314      Levis Karanja Kamau           Male                  1.0
9337   Wangari Kariuki Yvonne         Female                  1.0

[6839 rows x 3 columns]