In [1]:
import pandas as pd
import os

In [3]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [7]:
df=pd.read_excel('datasets/nyeri.xlsx')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: float64(6), object(2), str(12)
memory usage: 2.7+ MB

In [9]:
df.shape

(17567, 20)

In [10]:
df.columns

Index(['student_name', 'student_class', 'student_course', 'student_year',
       'student_gender', 'student_category', 'student_adm_no',
       'attachment_period', 'year', 'attachment_start_date',
       'attachment_end_date', 'company_name', 'sector_name',
       'placement_status', 'graded', 'assigned_manual',
       'student_workbehaviour_grading_score', 'student_skills_grading_score',
       'student_knowledge_grading_score', 'student_final_score'],
      dtype='str')

In [11]:
list(df.columns)

['student_name',
 'student_class',
 'student_course',
 'student_year',
 'student_gender',
 'student_category',
 'student_adm_no',
 'attachment_period',
 'year',
 'attachment_start_date',
 'attachment_end_date',
 'company_name',
 'sector_name',
 'placement_status',
 'graded',
 'assigned_manual',
 'student_workbehaviour_grading_score',
 'student_skills_grading_score',
 'student_knowledge_grading_score',
 'student_final_score']

In [13]:
statistical_summary=df.describe()

In [14]:
statistical_summary.to_excel('statistical_summary.xlsx')

In [15]:
#CHECK FOR MISSING VALUES
df.isnull().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [16]:
#SECONDA OPTION OF CHECKING MISSING VALUES
df.isna().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [18]:
#CHECK HOWMANY SHEET THE EXCEL IS CONTAINING
excel_file=pd.ExcelFile('datasets/nyeri.xlsx')
excel_file.sheet_names

['Worksheet']

In [19]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience'

In [20]:
os.path.exists(r'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience\\datasets\nyeri.xlsx')

True

In [21]:
df.isnull().values.any()

np.True_

In [22]:
df.isnull().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [23]:
df.isna().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [24]:
df.isna().values.any()

np.True_

In [25]:
df.isnull().sum().sum()

np.int64(69605)

In [26]:
df.isna().sum().sum()

np.int64(69605)

In [28]:
df.isna().sum()

student_name                               0
student_class                              0
student_course                             1
student_year                            7097
student_gender                           607
student_category                           0
student_adm_no                             0
attachment_period                       2416
year                                    2416
attachment_start_date                   2416
attachment_end_date                     2416
company_name                            5277
sector_name                             6382
placement_status                           0
graded                                     0
assigned_manual                            0
student_workbehaviour_grading_score    10309
student_skills_grading_score            9519
student_knowledge_grading_score        10021
student_final_score                    10728
dtype: int64

In [29]:
df["student_year"].isnull().values.any()

np.True_

In [30]:
df["student_year"].isnull().sum()

np.int64(7097)

In [36]:
students_missing_adm_no=df[df['student_year'].isnull()]

In [37]:
students_missing_adm_no.to_csv('students_missing_adm_no.csv',index=False)

In [38]:
df.loc[df['student_year'].isnull(),['student_name','student_class','student_adm_no','student_course']]

,student_name,student_class,student_adm_no,student_course
108,judy nyakio gichira,NNP/CMT6/25M2,42115,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...
109,judy nyakio gichira,NNP/CMT6/25M2,42115,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...
114,Wanjiru Kinuthia Talia,NNP/FDM4/24M1,42688,ARTISAN IN FASHION DESIGN AND GARMENT MAKING T...
143,Jesse Mwangi Kimondo,MVM424M1,43870,ARTISAN MOTOR VEHICLE MECHANICS -YEAR 1
144,Jesse Mwangi Kimondo,MVM424M1,43870,ARTISAN MOTOR VEHICLE MECHANICS -YEAR 1
...,...,...,...,...
17535,STUDENT 4 SEL6,SEL6/024/M\t,SEL64,Software Engineering Level 6
17551,Chrisjohn Githaiga Maina,\t\tNNP/WFB4/24M1,48549,WELDING AND FABRICATION LEVEL 4
17555,Karimi Wanja Kenneth,\t\tNNP/WFB4/24M1,49517,WELDING AND FABRICATION LEVEL 4
17561,Nahason Kihia Wangombe,\t\tNNP/WFB4/24M1,46319,WELDING AND FABRICATION LEVEL 4
17566,michae cheptoo,NNP/WFB5/23S1,46017,WELDING AND FABRICATION TECHNICIAN LEVEL 5

In [44]:
df[df['student_year'].isna() & df['student_gender'].isna()].shape

(219, 20)

In [45]:
df.loc[df['student_year'].isna() & df['student_gender'].isna()]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
3962,Adline Ndinda Kamala,NNP/cmt5/24s1,COSMETOLOGIST LEVEL 5,NaN,NaN,CBS,44439,MAY - JULY,2024.0,2024-05-01,2024-08-25,BLESSED SISTERS SALON,NaN,Placed,Graded,Assigned,13.8,60.0,9.4,83.0
3965,Anne Wanjira Maina,NNP/cmt5/24s2,COSMETOLOGIST LEVEL 5,NaN,NaN,CBS,43953,MAY - JULY,2024.0,2024-05-01,2024-08-25,RIDGEWAYS BARBER AND SPA,NaN,Placed,Graded,Assigned,20.0,57.1,20.0,97.0
4038,Muthoni Maina Mercy,NNP/cmt5/24s1,COSMETOLOGIST LEVEL 5,NaN,NaN,CBS,44355,MAY - JULY,2024.0,2024-05-01,2024-08-25,GLORIOUS BEAUTY PARLOUR,"BEAUTY, Cosmetology, Hair Dressing",Placed,Graded,Assigned,20.0,60.0,20.0,100.0
4039,Muthoni Maina Mercy,NNP/cmt5/24s1,COSMETOLOGIST LEVEL 5,NaN,NaN,CBS,44355,MAY - JULY,2024.0,2024-05-01,2024-08-25,GLORIUS SALON,NaN,Placed,Graded,Assigned,20.0,60.0,20.0,100.0
4067,Nyokabi Jane Wahome,NNP/cmt5/24s2,COSMETOLOGIST LEVEL 5,NaN,NaN,CBS,44304,MAY - JULY,2024.0,2024-05-01,2024-08-25,FABULAS BARBER,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17362,42678,PLB523M1,PLUMBER LEVEL 5,NaN,NaN,CBS,Munene Lewis Wachira,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17363,42872,PLB523M1,PLUMBER LEVEL 5,NaN,NaN,CBS,Kihara Jacob,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17364,42873,PLB523M1,PLUMBER LEVEL 5,NaN,NaN,CBS,Githua Jonhson Mwangi,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17365,42927,PLB523M1,PLUMBER LEVEL 5,NaN,NaN,CBS,Wambui Eric Mugendi,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN
17366,43030,PLB523M1,PLUMBER LEVEL 5,NaN,NaN,CBS,Muriithi Grace Terry Waithera,jan-april,2026.0,2026-01-01,2026-04-30,NaN,NaN,Not Placed,Not Graded,Not Assigned,NaN,NaN,NaN,NaN

In [46]:
df[df.isna()]

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df.columns[~df.isnull().any()].tolist()

['student_name',
 'student_class',
 'student_category',
 'student_adm_no',
 'placement_status',
 'graded',
 'assigned_manual']

In [53]:
df[~df.isnull().any(axis=1)].shape

(3998, 20)