In [1]:
import pandas as pd
import os

In [3]:
df=pd.read_excel('datasets/nyeri.xlsx')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: float64(6), object(2), str(12)
memory usage: 2.7+ MB

In [5]:
df.head(5)

,student_name,student_class,student_course,student_year,student_gender,student_category,student_adm_no,attachment_period,year,attachment_start_date,attachment_end_date,company_name,sector_name,placement_status,graded,assigned_manual,student_workbehaviour_grading_score,student_skills_grading_score,student_knowledge_grading_score,student_final_score
0,Allan Thiga Maina,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,54056,sept-dec,2025.0,2025-09-01,2025-12-31,SAMTECH ELECTRICALS,"Electrical & Electronics Engineering, Electric...",Placed,Not Graded,Assigned,10.0,38.6,NaN,NaN
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51732,sept-dec,2025.0,2025-09-01,2025-12-31,KARATINA SUBCOUNTY HOSPITAL,"HEALTH AND CARE, Health Care Giver, Healthcare...",Placed,Graded,Assigned,20.0,51.4,15.0,86.0
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53862,sept-dec,2025.0,2025-09-01,2025-12-31,NYERI RURINGU,NaN,Placed,Not Graded,Assigned,NaN,NaN,NaN,NaN
3,Isaac Kihagi Biru,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,51609,sept-dec,2025.0,2025-09-01,2025-12-31,KENYA POWER NYERI,"Electrical & Electronics Engineering, Electric...",Placed,Graded,Assigned,20.0,60.0,20.0,100.0
4,James Mugendi Mugi,NNP/EIT4/25J1,ELECTRICAL INSTALLATION TECHNOLOGY,1.0,Male,CBS,53842,sept-dec,2025.0,2025-09-01,2025-12-31,ITUMBE TEA FACTORY CO LTD,Electrical & Electronics Engineering,Placed,Graded,Assigned,20.0,42.9,16.7,80.0

In [7]:
#
df_subset=df.loc[
    df['placement_status']=='Placed',
    ['student_name','student_class','attachment_period','attachment_start_date']
]
df_subset

,student_name,student_class,attachment_period,attachment_start_date
0,Allan Thiga Maina,NNP/EIT4/25J1,sept-dec,2025-09-01
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,sept-dec,2025-09-01
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,sept-dec,2025-09-01
3,Isaac Kihagi Biru,NNP/EIT4/25J1,sept-dec,2025-09-01
4,James Mugendi Mugi,NNP/EIT4/25J1,sept-dec,2025-09-01
...,...,...,...,...
12290,MICHAEL KIAMA ERICK,NNP/WFB5/23S1,Sep - Dec,2024-09-01
12291,michael mugumo kamwaro,nnp/wfb5/25j2,sept-dec,2025-09-01
12292,michael mugumo kamwaro,nnp/wfb5/25j2,Sep - Dec,2024-09-01
12293,Nderitu Wanjiku Ephantus,NNP/WFB5/24S1,sept-dec,2025-09-01
12294,Victor Njuguna Mwaura,NNP/WFB5/24S1,sept-dec,2025-09-01

In [8]:
#SPLTING ATTACHMENT PERIOD INTO ATTACHMENT_START_MONTH AND ATTACHMENT_END_MONTH
df_subset[['attachment_start_month','attachment_end_month']]=(df_subset['attachment_period'].str.split('-',expand=True))

In [9]:
df_subset

,student_name,student_class,attachment_period,attachment_start_date,attachment_start_month,attachment_end_month
0,Allan Thiga Maina,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec
3,Isaac Kihagi Biru,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec
4,James Mugendi Mugi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec
...,...,...,...,...,...,...
12290,MICHAEL KIAMA ERICK,NNP/WFB5/23S1,Sep - Dec,2024-09-01,Sep,Dec
12291,michael mugumo kamwaro,nnp/wfb5/25j2,sept-dec,2025-09-01,sept,dec
12292,michael mugumo kamwaro,nnp/wfb5/25j2,Sep - Dec,2024-09-01,Sep,Dec
12293,Nderitu Wanjiku Ephantus,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec
12294,Victor Njuguna Mwaura,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec

In [12]:
#SPLITING STUDENT CLASS INTO 3 : (institution,course_code,category)
df_subset[['institution','course_code',]]=(df_subset['student_class'].str.split('/',n=1,expand=True))

In [13]:
df_subset

,student_name,student_class,attachment_period,attachment_start_date,attachment_start_month,attachment_end_month,institution,course_code
0,Allan Thiga Maina,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1
3,Isaac Kihagi Biru,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1
4,James Mugendi Mugi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1
...,...,...,...,...,...,...,...,...
12290,MICHAEL KIAMA ERICK,NNP/WFB5/23S1,Sep - Dec,2024-09-01,Sep,Dec,NNP,WFB5/23S1
12291,michael mugumo kamwaro,nnp/wfb5/25j2,sept-dec,2025-09-01,sept,dec,nnp,wfb5/25j2
12292,michael mugumo kamwaro,nnp/wfb5/25j2,Sep - Dec,2024-09-01,Sep,Dec,nnp,wfb5/25j2
12293,Nderitu Wanjiku Ephantus,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec,NNP,WFB5/24S1
12294,Victor Njuguna Mwaura,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec,NNP,WFB5/24S1

In [14]:
#SPLITING STUDENTS NAME INTO FIRSTNAME AND OTHER NAMES
df_subset[['firstname','other_names']]=(df_subset['student_name'].str.split(' ',n=1,expand=True))

In [15]:
df_subset

,student_name,student_class,attachment_period,attachment_start_date,attachment_start_month,attachment_end_month,institution,course_code,firstname,other_names
0,Allan Thiga Maina,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Allan,Thiga Maina
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Bernad,Ndirangu Mwangi
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Isaac,Kanja Kabuchu
3,Isaac Kihagi Biru,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Isaac,Kihagi Biru
4,James Mugendi Mugi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,James,Mugendi Mugi
...,...,...,...,...,...,...,...,...,...,...
12290,MICHAEL KIAMA ERICK,NNP/WFB5/23S1,Sep - Dec,2024-09-01,Sep,Dec,NNP,WFB5/23S1,MICHAEL,KIAMA ERICK
12291,michael mugumo kamwaro,nnp/wfb5/25j2,sept-dec,2025-09-01,sept,dec,nnp,wfb5/25j2,michael,mugumo kamwaro
12292,michael mugumo kamwaro,nnp/wfb5/25j2,Sep - Dec,2024-09-01,Sep,Dec,nnp,wfb5/25j2,michael,mugumo kamwaro
12293,Nderitu Wanjiku Ephantus,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec,NNP,WFB5/24S1,Nderitu,Wanjiku Ephantus
12294,Victor Njuguna Mwaura,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec,NNP,WFB5/24S1,Victor,Njuguna Mwaura

In [16]:
#RSPLIT
df_subset[['firstname_2','other_names_2']]=(df_subset['student_name'].str.rsplit(' ',n=1,expand=True))

In [17]:
df_subset

,student_name,student_class,attachment_period,attachment_start_date,attachment_start_month,attachment_end_month,institution,course_code,firstname,other_names,firstname_2,other_names_2
0,Allan Thiga Maina,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Allan,Thiga Maina,Allan Thiga,Maina
1,Bernad Ndirangu Mwangi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Bernad,Ndirangu Mwangi,Bernad Ndirangu,Mwangi
2,Isaac Kanja Kabuchu,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Isaac,Kanja Kabuchu,Isaac Kanja,Kabuchu
3,Isaac Kihagi Biru,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,Isaac,Kihagi Biru,Isaac Kihagi,Biru
4,James Mugendi Mugi,NNP/EIT4/25J1,sept-dec,2025-09-01,sept,dec,NNP,EIT4/25J1,James,Mugendi Mugi,James Mugendi,Mugi
...,...,...,...,...,...,...,...,...,...,...,...,...
12290,MICHAEL KIAMA ERICK,NNP/WFB5/23S1,Sep - Dec,2024-09-01,Sep,Dec,NNP,WFB5/23S1,MICHAEL,KIAMA ERICK,MICHAEL KIAMA,ERICK
12291,michael mugumo kamwaro,nnp/wfb5/25j2,sept-dec,2025-09-01,sept,dec,nnp,wfb5/25j2,michael,mugumo kamwaro,michael mugumo,kamwaro
12292,michael mugumo kamwaro,nnp/wfb5/25j2,Sep - Dec,2024-09-01,Sep,Dec,nnp,wfb5/25j2,michael,mugumo kamwaro,michael mugumo,kamwaro
12293,Nderitu Wanjiku Ephantus,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec,NNP,WFB5/24S1,Nderitu,Wanjiku Ephantus,Nderitu Wanjiku,Ephantus
12294,Victor Njuguna Mwaura,NNP/WFB5/24S1,sept-dec,2025-09-01,sept,dec,NNP,WFB5/24S1,Victor,Njuguna Mwaura,Victor Njuguna,Mwaura

In [21]:
df_subset.loc[:,['student_name','firstname','firstname_2','other_names','other_names_2']].head(3)

,student_name,firstname,firstname_2,other_names,other_names_2
0,Allan Thiga Maina,Allan,Allan Thiga,Thiga Maina,Maina
1,Bernad Ndirangu Mwangi,Bernad,Bernad Ndirangu,Ndirangu Mwangi,Mwangi
2,Isaac Kanja Kabuchu,Isaac,Isaac Kanja,Kanja Kabuchu,Kabuchu

In [25]:
#SPLITING WITH MULTIPLE SEPARATOR
df[['attachment_start_month','attachment_end_month']]=(df['attachment_period'].str.split(r'[/ - , _ ]',n=1, expand=True))

In [26]:
df.loc[:,['attachment_period','attachment_start_month','attachment_end_month']]

      attachment_period attachment_start_month attachment_end_month
0              sept-dec               sept-dec                  NaN
1              sept-dec               sept-dec                  NaN
2              sept-dec               sept-dec                  NaN
3              sept-dec               sept-dec                  NaN
4              sept-dec               sept-dec                  NaN
...                 ...                    ...                  ...
17562         May - Aug                    May                - Aug
17563          sept-dec               sept-dec                  NaN
17564         jan-april              jan-april                  NaN
17565         jan-april              jan-april                  NaN
17566         May - Aug                    May                - Aug

[17567 rows x 3 columns]

In [ ]:
df[['attachment_start_month','attachment_end_month']]=(df['attachment_period'].str.split('-',expand=True)).apply(lambda x: x.str.strip())