In [5]:
import pandas as pd
import os
from datetime import datetime

In [6]:
os.getcwd()

'C:\\Users\\Nyachomo\\OneDrive\\Desktop\\datascience\\datasets'

In [7]:
df=pd.read_excel('nyeri.xlsx')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  str
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: float64(6), object(2), str(12)
memory usage: 2.7+ MB

In [12]:
date=df.loc[
    df['attachment_start_date'].notna() & df['attachment_end_date'].notna(),
    ['student_name','student_adm_no','attachment_start_date','attachment_end_date']
].head(10)

In [13]:
date.to_excel('dates.xlsx')

In [14]:
os.path.exists('dates.xlsx')

True

In [16]:
df['attachment_start_date']=pd.to_datetime(df['attachment_start_date'],errors='coerce')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  datetime64[us]
 10  attachment_end_date                  15151 non-null  str
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: datetime64[us](1), float64(6), object(2), str(11)
memory usage: 2.7+ MB

In [18]:
df['attachment_end_date']=pd.to_datetime(df['attachment_end_date'], errors='coerce')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17567 entries, 0 to 17566
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   student_name                         17567 non-null  object
 1   student_class                        17567 non-null  str
 2   student_course                       17566 non-null  str
 3   student_year                         10470 non-null  float64
 4   student_gender                       16960 non-null  str
 5   student_category                     17567 non-null  str
 6   student_adm_no                       17567 non-null  object
 7   attachment_period                    15151 non-null  str
 8   year                                 15151 non-null  float64
 9   attachment_start_date                15151 non-null  datetime64[us]
 10  attachment_end_date                  15151 non-null  datetime64[us]
 11  company_name                         12290 non-null  str
 12  sector_name                          11185 non-null  str
 13  placement_status                     17567 non-null  str
 14  graded                               17567 non-null  str
 15  assigned_manual                      17567 non-null  str
 16  student_workbehaviour_grading_score  7258 non-null   float64
 17  student_skills_grading_score         8048 non-null   float64
 18  student_knowledge_grading_score      7546 non-null   float64
 19  student_final_score                  6839 non-null   float64
dtypes: datetime64[us](2), float64(6), object(2), str(10)
memory usage: 2.7+ MB

In [23]:
df[df['attachment_start_date'].isna() & (df['placement_status']=='Placed')]

Empty DataFrame
Columns: [student_name, student_class, student_course, student_year, student_gender, student_category, student_adm_no, attachment_period, year, attachment_start_date, attachment_end_date, company_name, sector_name, placement_status, graded, assigned_manual, student_workbehaviour_grading_score, student_skills_grading_score, student_knowledge_grading_score, student_final_score]
Index: []

In [26]:
#EXTRACTING DAY FROM DATE COLUMN
df1=df.loc[
    df['placement_status']=='Placed',
    ['student_name','student_adm_no','attachment_start_date']
    ]
df1.head(20)

                 student_name student_adm_no attachment_start_date
0           Allan Thiga Maina          54056            2025-09-01
1      Bernad Ndirangu Mwangi          51732            2025-09-01
2         Isaac Kanja Kabuchu          53862            2025-09-01
3           Isaac Kihagi Biru          51609            2025-09-01
4          James Mugendi Mugi          53842            2025-09-01
5       Jimmy Gitonga Mwendwa          18647            2025-09-01
6          Kimani Mutugu Evan          42057            2024-01-01
7   Macharia Wainaina Maxwell          53743            2025-09-01
8              Michael Kigano          54188            2025-09-01
9       Michael Ngugi Kariuki          53746            2025-09-01
10     Michael Odhiambo Owino          51805            2025-09-01
11    Mwangi Wambugu Fredrick          24252            2025-09-01
12      Peter Gichuru Kariuki          53773            2025-09-01
13           Roy Kiragu Githu          53971            2025-09-01
14       Ndungi Tobias Bachia          59097            2026-05-01
15   ABIGAEL Wambui Kinyanjui          50892            2025-09-01
16            BENEDETA MUTHEU          49752            2025-09-01
17                 BILAL IDDY          52613            2025-09-01
18           BLESSINGS MWENDE          49843            2025-09-01
19               David Maraka          48408            2025-05-01

In [27]:
df1['attachment_start_day']=df1['attachment_start_date'].dt.day

In [29]:
df1.head(20)

,student_name,student_adm_no,attachment_start_date,attachment_start_day
0,Allan Thiga Maina,54056,2025-09-01,1
1,Bernad Ndirangu Mwangi,51732,2025-09-01,1
2,Isaac Kanja Kabuchu,53862,2025-09-01,1
3,Isaac Kihagi Biru,51609,2025-09-01,1
4,James Mugendi Mugi,53842,2025-09-01,1
5,Jimmy Gitonga Mwendwa,18647,2025-09-01,1
6,Kimani Mutugu Evan,42057,2024-01-01,1
7,Macharia Wainaina Maxwell,53743,2025-09-01,1
8,Michael Kigano,54188,2025-09-01,1
9,Michael Ngugi Kariuki,53746,2025-09-01,1
10,Michael Odhiambo Owino,51805,2025-09-01,1
11,Mwangi Wambugu Fredrick,24252,2025-09-01,1
12,Peter Gichuru Kariuki,53773,2025-09-01,1
13,Roy Kiragu Githu,53971,2025-09-01,1
14,Ndungi Tobias Bachia,59097,2026-05-01,1
15,ABIGAEL Wambui Kinyanjui,50892,2025-09-01,1
16,BENEDETA MUTHEU,49752,2025-09-01,1
17,BILAL IDDY,52613,2025-09-01,1
18,BLESSINGS MWENDE,49843,2025-09-01,1
19,David Maraka,48408,2025-05-01,1

In [30]:
df1['attachment_start_month']=df1['attachment_start_date'].dt.month

In [31]:
df1

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month
0,Allan Thiga Maina,54056,2025-09-01,1,9
1,Bernad Ndirangu Mwangi,51732,2025-09-01,1,9
2,Isaac Kanja Kabuchu,53862,2025-09-01,1,9
3,Isaac Kihagi Biru,51609,2025-09-01,1,9
4,James Mugendi Mugi,53842,2025-09-01,1,9
...,...,...,...,...,...
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9
12291,michael mugumo kamwaro,45017,2025-09-01,1,9
12292,michael mugumo kamwaro,45017,2024-09-01,1,9
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9

In [33]:
df1['attachment_start_year']=df1['attachment_start_date'].dt.year

In [34]:
df1

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year
0,Allan Thiga Maina,54056,2025-09-01,1,9,2025
1,Bernad Ndirangu Mwangi,51732,2025-09-01,1,9,2025
2,Isaac Kanja Kabuchu,53862,2025-09-01,1,9,2025
3,Isaac Kihagi Biru,51609,2025-09-01,1,9,2025
4,James Mugendi Mugi,53842,2025-09-01,1,9,2025
...,...,...,...,...,...,...
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9,2024
12291,michael mugumo kamwaro,45017,2025-09-01,1,9,2025
12292,michael mugumo kamwaro,45017,2024-09-01,1,9,2024
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9,2025
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9,2025

In [35]:
df1['attachment_start_month_name']=df1['attachment_start_date'].dt.month_name()

In [36]:
df1.head(20)

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_start_month_name
0,Allan Thiga Maina,54056,2025-09-01,1,9,2025,September
1,Bernad Ndirangu Mwangi,51732,2025-09-01,1,9,2025,September
2,Isaac Kanja Kabuchu,53862,2025-09-01,1,9,2025,September
3,Isaac Kihagi Biru,51609,2025-09-01,1,9,2025,September
4,James Mugendi Mugi,53842,2025-09-01,1,9,2025,September
5,Jimmy Gitonga Mwendwa,18647,2025-09-01,1,9,2025,September
6,Kimani Mutugu Evan,42057,2024-01-01,1,1,2024,January
7,Macharia Wainaina Maxwell,53743,2025-09-01,1,9,2025,September
8,Michael Kigano,54188,2025-09-01,1,9,2025,September
9,Michael Ngugi Kariuki,53746,2025-09-01,1,9,2025,September
10,Michael Odhiambo Owino,51805,2025-09-01,1,9,2025,September
11,Mwangi Wambugu Fredrick,24252,2025-09-01,1,9,2025,September
12,Peter Gichuru Kariuki,53773,2025-09-01,1,9,2025,September
13,Roy Kiragu Githu,53971,2025-09-01,1,9,2025,September
14,Ndungi Tobias Bachia,59097,2026-05-01,1,5,2026,May
15,ABIGAEL Wambui Kinyanjui,50892,2025-09-01,1,9,2025,September
16,BENEDETA MUTHEU,49752,2025-09-01,1,9,2025,September
17,BILAL IDDY,52613,2025-09-01,1,9,2025,September
18,BLESSINGS MWENDE,49843,2025-09-01,1,9,2025,September
19,David Maraka,48408,2025-05-01,1,5,2025,May

In [37]:
df1['attachment_start_month_abbr']=df1['attachment_start_date'].dt.strftime('%b')

In [38]:
df1.tail(20)

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_start_month_name,attachment_start_month_abbr
12275,Chrispas Kiongo Maina,57314,2026-05-01,1,5,2026,May,May
12276,James Mugo Kariuki,55230,2026-01-01,1,1,2026,January,Jan
12277,John Wycliffe Wanja,42908,2026-01-01,1,1,2026,January,Jan
12278,John Wycliffe Wanja,42908,2025-01-01,1,1,2025,January,Jan
12279,John Wycliffe Wanja,42908,2024-01-01,1,1,2024,January,Jan
12280,Kevin Mwangi Kihara,37024,2026-01-01,1,1,2026,January,Jan
12281,Kevin Mwangi Kihara,37024,2023-09-09,9,9,2023,September,Sep
12282,Martin Karanja Mwangi,55095,2026-01-01,1,1,2026,January,Jan
12283,Muriuki Muriithi Valentino,47141,2025-01-01,1,1,2025,January,Jan
12284,Wycliffe Ngugi Mbogo,38978,2026-05-01,1,5,2026,May,May
12285,Wycliffe Ngugi Mbogo,38978,2024-09-01,1,9,2024,September,Sep
12286,Eliel Mwangi Mathenge,50435,2026-01-01,1,1,2026,January,Jan
12287,Elijah Muchiri Nderitu,52706,2025-09-01,1,9,2025,September,Sep
12288,Gichuki Simon,51346,2026-01-01,1,1,2026,January,Jan
12289,Gitahi Nganga Patrick,50834,2025-09-01,1,9,2025,September,Sep
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9,2024,September,Sep
12291,michael mugumo kamwaro,45017,2025-09-01,1,9,2025,September,Sep
12292,michael mugumo kamwaro,45017,2024-09-01,1,9,2024,September,Sep
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9,2025,September,Sep
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9,2025,September,Sep

In [39]:
df1['week_day']=df1['attachment_start_date'].dt.day_name()

In [40]:
df1.tail()

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_start_month_name,attachment_start_month_abbr,week_day
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9,2024,September,Sep,Sunday
12291,michael mugumo kamwaro,45017,2025-09-01,1,9,2025,September,Sep,Monday
12292,michael mugumo kamwaro,45017,2024-09-01,1,9,2024,September,Sep,Sunday
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9,2025,September,Sep,Monday
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9,2025,September,Sep,Monday

In [43]:
df1['week_day_2']=df1['attachment_start_date'].dt.strftime('%a')

In [44]:
df1.tail()

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_start_month_name,attachment_start_month_abbr,week_day,week_day_2
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9,2024,September,Sep,Sunday,Sun
12291,michael mugumo kamwaro,45017,2025-09-01,1,9,2025,September,Sep,Monday,Mon
12292,michael mugumo kamwaro,45017,2024-09-01,1,9,2024,September,Sep,Sunday,Sun
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9,2025,September,Sep,Monday,Mon
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9,2025,September,Sep,Monday,Mon

In [45]:
df1['quarter']=df1['attachment_start_date'].dt.quarter

In [46]:
df1.tail()

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_start_month_name,attachment_start_month_abbr,week_day,week_day_2,quarter
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9,2024,September,Sep,Sunday,Sun,3
12291,michael mugumo kamwaro,45017,2025-09-01,1,9,2025,September,Sep,Monday,Mon,3
12292,michael mugumo kamwaro,45017,2024-09-01,1,9,2024,September,Sep,Sunday,Sun,3
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9,2025,September,Sep,Monday,Mon,3
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9,2025,September,Sep,Monday,Mon,3

In [47]:
df1['week']=df1['attachment_start_date'].dt.isocalendar().week

In [48]:
df1.tail()

,student_name,student_adm_no,attachment_start_date,attachment_start_day,attachment_start_month,attachment_start_year,attachment_start_month_name,attachment_start_month_abbr,week_day,week_day_2,quarter,week
12290,MICHAEL KIAMA ERICK,44815,2024-09-01,1,9,2024,September,Sep,Sunday,Sun,3,35
12291,michael mugumo kamwaro,45017,2025-09-01,1,9,2025,September,Sep,Monday,Mon,3,36
12292,michael mugumo kamwaro,45017,2024-09-01,1,9,2024,September,Sep,Sunday,Sun,3,35
12293,Nderitu Wanjiku Ephantus,49920,2025-09-01,1,9,2025,September,Sep,Monday,Mon,3,36
12294,Victor Njuguna Mwaura,49907,2025-09-01,1,9,2025,September,Sep,Monday,Mon,3,36